---
# Uninstall Community Certificate Manager
# https://docs.openshift.com/container-platform/4.12/security/cert_manager_operator/cert-manager-operator-uninstall.html
# -----------------------------------------------------------------------------
- name: "Uninstall: Delete Community Certificate Manager namespace: {{ cert_manager_operator_namespace }}"
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ cert_manager_operator_namespace }}"
    wait: true
    wait_timeout: 600

- name: "Uninstall: Delete Community Certificate Manager namespace: {{ cert_manager_namespace }}"
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ cert_manager_namespace }}"
    wait: true
    wait_timeout: 600

# Delete Certificate CRDs
# -------------------------------------------------------------------------------------
- name: "Uninstall: Delete Community Certificate Manager CRDs"
  kubernetes.core.k8s:
    state: absent
    api_version: "apiextensions.k8s.io/v1"
    kind: "CustomResourceDefinition"
    name: "{{ item }}.cert-manager.io"
  loop:
    - certificates
    - certificaterequests
    - clusterissuers
    - issuers
