---
# Create PVC
# -----------------------------------------------------------------------------
- name: "Create PVC for SEAS"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "s0-ibm-seas-pvc-{{ my_serial }}"
        namespace: "{{ seas_namespace }}"
        labels:
          app.kubernetes.io/app-instance: "s0-ibm-seas-pvc-{{ my_serial }}"
          app.kubernetes.io/name: ibm-seas
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ storage_class_matrix[seas_storage_class].rwo }}"
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

- name: Wait for PVC to be Bound
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    name: "s0-ibm-seas-pvc-{{ my_serial }}"
    namespace: "{{ seas_namespace }}"
  register: pvc_info
  until: pvc_info.resources[0].status.phase == 'Bound'
  retries: 15  # Total retries will be 15 * 20s = 300s (5 minutes)
  delay: 20     # Wait for 20 seconds between each retry

- name: Debug PVC
  ansible.builtin.debug:
    msg: "PVC is ready"
