---
- name: "Set fact helm file"
  ansible.builtin.set_fact:
    my_helmfile: "{{ my_workdir }}/ibm-seas-{{ compatibility_matrix[seas_version].helm_version }}.tgz"
    my_valuesfile: "{{ my_workdir }}/myseas_values-{{ my_serial }}.yml"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_valuesfile }}"
    mode: "0640"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "Image Repository  ................. {{ compatibility_matrix[seas_version].image_repository }}"
      - "Image Tag         ................. {{ compatibility_matrix[seas_version].image_tag }}"
      - "helm install --timeout 10m0s -f {{ my_valuesfile }} -n {{ seas_namespace }} s0 {{ my_helmfile }}"

- name: Run Helm install command
  ansible.builtin.command:
    cmd: "helm install --timeout 10m0s -f {{ my_valuesfile }} -n {{ seas_namespace }} s0 {{ my_helmfile }}"
  register: helm_cout
  changed_when: helm_cout.rc != 0

# # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
# - name: Deploy SEAS chart from local path
#   kubernetes.core.helm:
#     name: "{{ my_helm_release }}"
#     chart_ref: "{{ my_helm.chart }}"
#     release_namespace: "{{ seas_namespace }}"
#     wait: True
#     timeout: "{{ my_helm.timeout }}"
#     values_files: "{{ my_helm.values }}"

- name: "Lookup SEAS Pod"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ seas_namespace }}"
    label_selectors:
      - release=s0
    wait: true
    wait_sleep: 30
    wait_timeout: 300 # 5 mins until we give up waiting for the pod to get into the expected state
    wait_condition:
      type: Ready
      status: "True"
  register: seas_pod

- name: Configure facts
  ansible.builtin.set_fact:
    seas_pod_name: "{{ seas_pod.resources[0].metadata.name }}"

- name: "IBM Sterling SEAS Summary:"
  ansible.builtin.debug:
    msg:
      - "IBM Sterling SEAS status ............................ Ready!"
      - "SEAS namespace ...................................... {{ seas_namespace }}"
      - "Pod name ............................................ {{ seas_pod_name }}"
      - "For username and password check secret .............. {{ seas_secret }}'"
