---
# - name: Check for required environment variables
#   ansible.builtin.assert:
#     that:
#       # NAMESPACE
#       - lookup('env', 'OPENLDAP_NAMESPACE') != ""
#     fail_msg: "One or more required environment variables are not defined"


# 1. Fail if required parameters are not set
# -----------------------------------------------------------------------------
- name: "Fail if required properties have not been provided"
  ansible.builtin.assert:
    that:
      - openldap_namespace is defined and openldap_namespace != ""
      - ldp_base_dn is defined and ldp_base_dn != ""
    fail_msg: "One or more required properties have not been set"
