---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for OpenLDAP"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ openldap_namespace }}"
        labels:
          name: openldap
  register: cout

# Create Secrets
# -----------------------------------------------------------------------------
- name: Create Secrets for OpenLDAP
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: openldap-secret
        namespace: "{{ openldap_namespace }}"
        labels:
          app: openldap
      type: Opaque
      stringData:
        LDAP_ADMIN_PASSWORD: "{{ ldp_admin_password }}"
        LDAP_BIND_PASSWORD: "{{ ldp_bind_password }}"
        LDAP_UNIVERSAL_PASSWORD: "{{ ldp_universal_password }}"

# # Create ServiceAccount
# -----------------------------------------------------------------------------
- name: Create Service Account for OpenLDAP
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: openldap-sa
        namespace: "{{ openldap_namespace }}"

# Create Role Binding
# -----------------------------------------------------------------------------
- name: Create Role Binding for OpenLDAP
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: 'openldap-anyuid'
        namespace: "{{ openldap_namespace }}"
        labels:
          app: openldap
      subjects:
        - kind: ServiceAccount
          name: openldap-sa
          namespace: "{{ openldap_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: 'system:openshift:scc:anyuid'
