---
- name: Define Storage Class for OpenLDAP
  ansible.builtin.set_fact:
    oldp_storageclass: "{{ storage_class_matrix[my_storage_class].rwx }}"

# Create PVC
# -----------------------------------------------------------------------------
- name: Apply PVC openldap-data-pvc
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: openldap-data-pvc
        namespace: "{{ openldap_namespace }}"
        labels:
          app: openldap
          app.kubernetes.io/name: openldap
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ oldp_storageclass }}"
        # volumeMode: Filesystem
        resources:
          requests:
            storage: 100Mi

- name: Wait for PVC to be Bound openldap-data-pvc
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    name: openldap-data-pvc
    namespace: "{{ openldap_namespace }}"
  register: pvc_info
  until: pvc_info.resources[0].status.phase == 'Bound'
  retries: 15  # Total retries will be 15 * 20s = 300s (5 minutes)
  delay: 20     # Wait for 20 seconds between each retry

- name: Debug PVC
  ansible.builtin.debug:
    msg: "PVC is ready"
