---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Define Storage
  ansible.builtin.include_tasks: 03_define_storage.yml

- name: Create Storage
  ansible.builtin.include_tasks: 04_create_storage.yml

- name: Configure ConfigMaps
  ansible.builtin.include_tasks: 05_configure_configmaps.yml

- name: Deploy OpenLDAP
  ansible.builtin.include_tasks: 06_deploy_openldap.yml
