---
ssp_cm_url: "{{ lookup('env', 'SSP_CM_URL') }}"
ssp_engine_host: "{{ lookup('env', 'SSP_ENGINE_HOST') }}"
ssp_engine_port: "{{ lookup('env', 'SSP_ENGINE_PORT') | default('63366', true) }}"

ssp_instanceid: "{{ lookup('env', 'SSP_INSTANCEID') | default('dev01', true) }}"
ssp_admin_user: "{{ lookup('env', 'SSP_ADMIN_USER') | default('admin', true) }}"
ssp_admin_password: "{{ lookup('env', 'SSP_ADMIN_PASSWORD') | default('Password123!', true) }}"

ssp_namespace: "ibm-ssp-{{ ssp_instanceid }}-engine"
ssp_service: "s0-ibm-ssp-engine"
ssp_cm_namespace: "ibm-ssp-{{ ssp_instanceid }}-cm"
ssp_cm_route: "s0-ibm-ssp-cm"

ssp_cfg:
  engine:
    enabled: true
  cd:
    enabled: false
    policy: false
    netmap: false
    adapter: false
  sftp:
    enabled: false
    policy: false
    netmap: false
    adapter: false
  http:
    enabled: false
    policy: false
    netmap: false
    adapter: false
