---
- name: Check if Connect:Direct is already up and running
  ansible.builtin.shell: "ps -ef | grep cdpmgr | grep -v grep"
  changed_when: true
  register: __cd_running
  ignore_errors: true

- name: Check if Product already Installed?
  ansible.builtin.stat:
    path: "{{ __cd_install_path }}/ndm/cfg/{{ __cd_nodename }}/initparm.cfg"
  register: __cd_installed
# when: not __cd_installed.stat.exists
