- name: "Download and unzip installation {{ __package_name }} to the {{ __extraction_folder }}"
  ansible.builtin.unarchive:
    src: "{{ __repository_url }}/{{ __package_name }}"
    dest: "{{ __extraction_folder }}"
    remote_src: true
  register: download_and_unpack_pkgs
  until: download_and_unpack_pkgs is succeeded
  retries: 3
