---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for phpLdapWebAdmin"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ phpldapadmin_namespace }}"
        labels:
          name: phpldapadmin
  register: cout

# Create Secrets
# -----------------------------------------------------------------------------
- name: Create Secrets for phpLdapWebAdmin
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: phpldapadmin-secret
        namespace: "{{ phpldapadmin_namespace }}"
        labels:
          app: phpldapadmin
      type: Opaque
      stringData:
        LDAP_ADMIN_PASSWORD: "{{ ldp_admin_password }}"

# # Create ServiceAccount
# -----------------------------------------------------------------------------
- name: Create Service Account for phpLdapWebAdmin
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: phpldapadmin-sa
        namespace: "{{ phpldapadmin_namespace }}"

# Create Role Binding
# -----------------------------------------------------------------------------
- name: Create Role Binding for phpLdapWebAdmin
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: 'phpldapadmin-anyuid'
        namespace: "{{ phpldapadmin_namespace }}"
        labels:
          app: phpldapadmin
      subjects:
        - kind: ServiceAccount
          name: phpldapadmin-sa
          namespace: "{{ phpldapadmin_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: 'system:openshift:scc:anyuid'
