---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Deploy phpLdapWebAdmin
  ansible.builtin.include_tasks: 03_deploy_phpldap.yml
