---
- name: Check for required environment variables
  ansible.builtin.assert:
    that:
      # Sterling B2B
      - lookup('env', 'SI_NAMESPACE') != ""
      # IBM
      - lookup('env', 'ENTITLED_REGISTRY_KEY') != ""   
      # # SLS
      # - (lookup('env', 'SLS_LICENSE_ID') != "" and lookup('env', 'SLS_LICENSE_FILE') != "") or
      #   (lookup('env', 'SLS_ENTITLEMENT_FILE') != "")
    fail_msg: "One or more required environment variables are not defined"

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if si_namespace is not provided"
  ansible.builtin.assert:
    that: si_namespace is defined and si_namespace != ""
    fail_msg: "si_namespace property is required"

- name: "Fail if entitled_registry_key is not provided"
  ansible.builtin.assert:
    that: entitled_registry_key is defined and entitled_registry_key != ""
    fail_msg: "entitled_registry_key property is required"

# Debug
# -----------------------------------------------------------------------------
- name: Debug
  debug:
    msg:
      - "Kubernets Namespace ................. {{ si_namespace }}"
