---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for Sterling B2Bi"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ si_namespace }}"
  register: cout

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: Create '{{ si_registry_secret }}' secret content
  no_log: false
  vars:
    entitledAuthStr: "{{ entitled.registry_user }}:{{ entitled.registry_key }}"
    entitledAuth: "{{ entitledAuthStr | b64encode }}"
    content:
      - "{\"auths\":{\"{{ entitled.registry }}\":{\"username\":\"{{ entitled.registry_user }}\",\"password\":\"{{ entitled.registry_key }}\",\"email\":\"{{ entitled.registry_user }}\",\"auth\":\"{{ entitledAuth }}\"}"
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate '{{ si_registry_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ si_registry_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: ibm_registry_secret_cout

- name: "Generate '{{ si_system_passphrase_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_system_passphrase_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        SYSTEM_PASSPHRASE: "{{ si_system_passphrase | b64encode }}"
  register: si_system_passphrase_secret_cout

- name: "Generate '{{ si_liberty_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_liberty_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        LIBERTY_KEYSTORE_PASSWORD: "{{ si_libertykeystorepassword | b64encode }}"
  register: si_liberty_secret_cout
