---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for Sterling B2Bi"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ si_namespace }}"
  register: cout

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: Create '{{ si_registry_secret }}' secret content
  no_log: false
  vars:
    entitledAuthStr: "{{ entitled_registry_user }}:{{ entitled_registry_key }}"
    entitledAuth: "{{ entitledAuthStr | b64encode }}"
    content:
      - "{\"auths\":{\"{{ entitled_registry }}\":{\"username\":\"{{ entitled_registry_user }}\",\"password\":\"{{ entitled_registry_key }}\",\"email\":\"{{ entitled_registry_user }}\",\"auth\":\"{{ entitledAuth }}\"}"
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate '{{ si_registry_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ si_registry_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: ibm_registry_secret_cout

- name: "Generate '{{ si_system_passphrase_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_system_passphrase_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        SYSTEM_PASSPHRASE: "{{ si_system_passphrase | b64encode }}"
  register: si_system_passphrase_secret_cout

- name: "Generate '{{ si_db_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_db_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        DB_USER: "{{ si_dbuser | b64encode }}"
        DB_PASSWORD: "{{ si_dbpassword | b64encode }}"
  register: si_db_secret_cout

- name: "Generate '{{ si_jms_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_jms_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        JMS_USERNAME: "{{ si_jmsuser | b64encode }}"
        JMS_PASSWORD: "{{ si_jmspassword | b64encode }}"
        JMS_KEYSTORE_PASSWORD: "{{ si_jmskeystorepassword | b64encode }}"
        JMS_TRUSTSTORE_PASSWORD: "{{ si_jmstruststorepassword | b64encode }}"
  register: si_jms_secret_cout

- name: "Generate '{{ si_liberty_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ si_liberty_secret }}"
        namespace: "{{ si_namespace }}"
      data:
        LIBERTY_KEYSTORE_PASSWORD: "{{ si_libertykeystorepassword | b64encode }}"
  register: si_liberty_secret_cout
