# mkdocs serve

site_name: IBM Sterling Devops Ansible
site_url: https://ibm-sterling-devops.github.io/ansible-ibm-sterling

repo_name: GitHub
repo_url: https://github.com/ibm-sterling-devops/ansible-ibm-sterling
edit_uri: blob/main/docs/

nav:
  - "Getting Started": 
    - "Home": index.md
    - "Requirements": 
      - "MacOS": requirements-macos.md
      - "Redhat Linux": requirements-rh.md
      - "Ubuntu Linux": requirements-ubuntu.md
      - "MS Windows": requirements-windows.md
  - "Playbooks: Standard":
    - "Install IBM Connect:Direct 6.2.x": playbooks/setup_cd.md
    - "Install IBM Sterling B2B Integrator 6.1.2": playbooks/setup_b2b.md
  - "Playbooks: RedHat OpenShift":
    - "Deploy IBM Connect:Direct 6.3.x": playbooks/deploy_ocp_cd.md
    - "Deploy IBM Connect:Direct WebServices": playbooks/deploy_ocp_cdws.md
    - "Deploy IBM Sterling Transformation Server (ITX RS)": playbooks/deploy_ocp_itx_rs.md
    - "Deploy IBM Sterling Transformation Advanced (ITXA)": playbooks/deploy_ocp_itxa.md
    - "Deploy IBM Sterling B2B Integrator": playbooks/deploy_ocp_sb2b.md
    - "Deploy IBM Sterling Control Center Monitor/Director (CCM/CCD)": playbooks/deploy_ocp_scc.md
    - "Deploy IBM Sterling External Authentication Server (SEAS)": playbooks/deploy_ocp_seas.md
    - "Deploy IBM Sterling Secure Proxy Server (SSP)": playbooks/deploy_ocp_ssp.md
  - "Playbooks: Tools":
      - "Deploy CloudBeaver CE": playbooks/tools_deploy_cloudbeaver.md
      - "Deploy Kafka": playbooks/tools_deploy_kafka.md
      - "Deploy Kowl": playbooks/tools_deploy_kowl.md
      - "Deploy MinIO S3 storage": playbooks/tools_deploy_minio.md
      # - "Deploy MongoDB": playbooks/tools_deploy_mongodb.md
      - "Deploy OpenLDAP as LDAP Server": playbooks/tools_deploy_openldap.md
  - "Roles:":
    - "cd_deploy": roles/cd_deploy.md
    - "cdws_deploy": roles/cdws_deploy.md
    - "itx_rs_deploy": roles/itx_rs_deploy.md
    - "itxa_deploy": roles/itxa_deploy.md
    - "itxa_deploy_db2": roles/itxa_deploy_db2.md
    - "itxa_setup_db2": roles/itxa_setup_db2.md
    - "pem_deploy_db2": roles/pem_deploy_db2.md
    - "pem_deploy_mq": roles/pem_deploy_mq.md
    - "sb2bi_deploy": roles/sb2bi_deploy.md
    - "sb2bi_deploy_db2": roles/sb2bi_deploy_db2.md
    - "sb2bi_deploy_mq": roles/sb2bi_deploy_mq.md
    - "sb2bi_prebuiltdb_db2": roles/sb2bi_prebuiltdb_db2.md
    - "sb2bi_setup_db2": roles/sb2bi_setup_db2.md
    - "scc_deploy": roles/scc_deploy.md
    - "scc_deploy_db2": roles/scc_deploy_db2.md
    - "scc_deploy_mq": roles/scc_deploy_mq.md
    - "scc_setup_db2": roles/scc_setup_db2.md
    - "seas_deploy": roles/seas_deploy.md
    - "ssp_cm_deploy": roles/ssp_cm_deploy.md
    - "ssp_config": roles/ssp_config.md
    - "ssp_deploy": roles/ssp_deploy.md
    - "ssp_ps_deploy": roles/ssp_ps_deploy.md
  - "Roles: Tools":
    - "cert_manager": roles/cert_manager.md
    - "cloudbeaver": roles/cloudbeaver.md
    - "kafka": roles/kafka.md
    - "kowl": roles/kowl.md
    - "minio": roles/minio.md
    - "openldap": roles/openldap.md
    - "phpldapadmin": roles/phpldapadmin.md
  - "Others": 
    - "Known Problems": others/known_problems.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
