# mkdocs serve

site_name: IBM Sterling Devops Ansible
site_url: https://ibm-sterling-devops.github.io/ansible-ibm-sterling

repo_name: GitHub
repo_url: https://github.com/ibm-sterling-devops/ansible-ibm-sterling
edit_uri: blob/main/docs/

nav:
  - "Home":
    - "Getting Started": index.md
    - "Requirements":
      - "MacOS": requirements-macos.md
      - "Redhat Linux": requirements-rh.md
      - "Ubuntu Linux": requirements-ubuntu.md
      - "MS Windows": requirements-windows.md
  - "Deploy on RedHat OpenShift":
      - "Connect:Direct 6.x": playbooks/deploy_ocp_cd.md
      - "Connect:Direct WebServices": playbooks/deploy_ocp_cdws.md
      - "Sterling B2B Integrator": playbooks/deploy_ocp_sb2b.md
      - "Sterling Control Center Monitor/Director (CCM/CCD)": playbooks/deploy_ocp_scc.md
      - "Sterling Secure Proxy Server (SSP)": playbooks/deploy_ocp_ssp.md
      - "Sterling External Authentication Server (SEAS)": playbooks/deploy_ocp_seas.md
      - "IBM Sterling Transformation Server (ITX RS)": playbooks/deploy_ocp_itx_rs.md
      - "IBM Sterling Transformation Advanced (ITXA)": playbooks/deploy_ocp_itxa.md
  - "Standard Install":
      - "Install IBM Connect:Direct 6.2.x": playbooks/setup_cd.md
      - "Install IBM Sterling B2B Integrator 6.1.2": playbooks/setup_b2b.md
  - "Tools":
      - "CloudBeaver CE": playbooks/tools_deploy_cloudbeaver.md
      - "Kafka": playbooks/tools_deploy_kafka.md
      - "Kowl": playbooks/tools_deploy_kowl.md
      - "MinIO S3 storage": playbooks/tools_deploy_minio.md
      # - "Deploy MongoDB": playbooks/tools_deploy_mongodb.md
      - "Deploy OpenLDAP as LDAP Server": playbooks/tools_deploy_openldap.md
  - "All Roles": all_roles.md
  - "Others":
    - "Known Problems": others/known_problems.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.expand
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
