# mkdocs serve

site_name: IBM Sterling Devops Ansible
site_url: https://ibm-sterling-devops.github.io/ansible-ibm-sterling

repo_name: GitHub
repo_url: https://github.com/ibm-sterling-devops/ansible-ibm-sterling
edit_uri: blob/main/docs/

nav:
  - "Getting Started": 
    - "Home": index.md
    - "Requirements": requirements.md
  - "Playbooks: Standard":
    - "Install IBM Connect:Direct 6.2.x": playbooks/setup_cd.md
    - "Install IBM Sterling B2B Integrator 6.1.2  - one node only": playbooks/setup_b2b.md
  #     - "Install IBM DB2 11.5.x and setup Sterling B2Bi Database": 
  #     - "Install Nginx as HTTP server for Repository|    
  - "Playbooks: RedHat OpenShift":
    - "Deploy IBM Connect:Direct 6.3.x": playbooks/deploy_ocp_cd.md
    - "Deploy IBM Connect:Direct WebServices": playbooks/deploy_ocp_cdws.md
    - "Deploy IBM Sterling Transformation Server (ITX RS)": playbooks/deploy_ocp_itx_rs.md
    - "Deploy IBM Sterling Transformation Advanced (ITXA)": playbooks/deploy_ocp_itxa.md
    - "Deploy IBM Sterling B2B Integrator": playbooks/deploy_ocp_sb2b.md
    - "Deploy IBM Sterling Control Center Monitor/Director (CCM/CCD)": playbooks/deploy_ocp_scc.md
    - "Deploy IBM Sterling External Authentication Server (SEAS)": playbooks/deploy_ocp_seas.md
    - "Deploy IBM Sterling Secure Proxy Server (SSP)": playbooks/deploy_ocp_ssp.md
  # - "Playbooks for Tools":
  #     - "Deploy CloudBeaver CE to manage databases": 
  #     - "Deploy OpenLDAP as LDAP Server": 
  - "Roles:":
    - "cd_deploy": roles/cd_deploy
    - "cdws_deploy": roles/cdws_deploy
    - "itx_rs_deploy": roles/itx_rs_deploy
    - "itxa_deploy": roles/itxa_deploy
    - "sb2bi_deploy": roles/sb2bi_deploy
    - "sb2bi_deploy_db2": roles/sb2bi_deploy_db2
    - "sb2bi_deploy_mq": roles/sb2bi_deploy_mq
    - "sb2bi_setup_db2": roles/sb2bi_setup_db2
    - "scc_deploy": roles/scc_deploy
    - "scc_deploy_db2": roles/scc_deploy_db2
    - "scc_deploy_mq": roles/scc_deploy_mq
    - "scc_setup_db2": roles/scc_setup_db2
    - "seas_deploy": roles/seas_deploy
    - "ssp_cm_deploy": roles/ssp_cm_deploy
    - "ssp_config": roles/ssp_config
    - "ssp_deploy": roles/ssp_deploy
    - "ssp_ps_deploy": roles/ssp_ps_deploy
# - "Roles": Utilities":
#     - "cloudbeaver"": roles/cloudbeaver.md
  - "Others": 
    - "Known Problems": known_problems.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
