---
# Get values from Environment Variables
# -----------------------------------------------------------------------------
si_instanceid: "{{ lookup('env', 'SI_INSTANCEID') }}"
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') }}"
mq_namespace: "{{ lookup('env', 'MQ_NAMESPACE') }}"

si_licenseType: "{{ lookup('env', 'SI_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod
si_system_passphrase: "{{ lookup('env', 'SI_SYSTEM_PASSPHRASE') | default('passwOrd', true) }}"

si_dbvendor: "{{ lookup('env', 'SI_DBVENDOR') }}"
si_dbhost: "{{ lookup('env', 'SI_DBHOST') }}"
si_dbport: "{{ lookup('env', 'SI_DBPORT') }}"
si_dbname: "{{ lookup('env', 'SI_DBNAME') }}"
si_dbuser: "{{ lookup('env', 'SI_DBUSER') }}"
si_dbpassword: "{{ lookup('env', 'SI_DBPASSWORD') }}"
si_oracleUseServiceName: "{{ lookup('env', 'SI_ORACLESERVICENAME', default('false')) }}"

si_adminMailAddr: "{{ lookup('env', 'SI_ADMIN_MAILADDR') | default('admin@company.com', true) }}"
si_adminSmtpHost: "{{ lookup('env', 'SI_ADMIN_SMTPHOST') | default('smtp.company.com', true) }}"

si_jmsuser: "{{ lookup('env', 'SI_JMS_USERNAME') }}"
si_jmspassword: "{{ lookup('env', 'SI_JMS_PASSWORD') }}"
si_jmskeystorepassword: "{{ lookup('env', 'SI_JMS_KEYSTORE_PASSWORD') }}"
si_jmstruststorepassword: "{{ lookup('env', 'SI_JMS_TRUSTSTORE_PASSWORD') }}"

si_libertykeystorepassword: "{{ lookup('env', 'SI_LIBERTY_KEYSTORE_PASSWORD') | default('changeit', true) }}"

# Entitlement
# -----------------------------------------------------------------------------
entitled:
  registry: "cp.icr.io/cp"
  registry_user: cp
  registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Defaults for B2Bi instances.
# -----------------------------------------------------------------------------
my_workdir: /tmp

si_namespace: "sterling-b2bi-app-{{ si_instanceid }}"
si_version: "6.2.0.0"

si_registry_secret: si-ibm-registry
si_system_passphrase_secret: si-system-passphrase-secret
si_db_secret: si-db-secret
si_jms_secret: si-jms-secret
si_liberty_secret: si-liberty-secret
si_helm_release: si00

db2_secret: mydb2-secret
db2_id: mydb2
mq_secret: mymq-secret

# Helm Variables
# -----------------------------------------------------------------------------
si_helm:
  timeout: "60m0s"


# Sterling B2Bi Compatibility Matrix
# -----------------------------------------------------------------------------
compatibility_matrix:
  6.2.0.0:
    helm_version: "3.0.0"
    global:
      image:
        tag: "6.2.0.0"
    resourcesInit:
      image:
        tag: "6.2.0.0"
    dataSetup:
      image:
        tag: "6.2.0.0"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: "10.1.1.1.20221116"
      itxaIntegration:
        image:
          tag: "10.0.1.8"
        resourcesInit:
          tag: "10.0.1.8"
    test:
      image:
        tag: '1.1.62'
    purge:
      image:
        tag: "6.2.0.0"
    documentService:
      image:
        tag: 1.0.0.0
  6.1.2.5:
    helm_version: "2.1.6"
    global:
      image:
        tag: "6.1.2.5"
    resourcesInit:
      image:
        tag: "6.1.2.5"
    dataSetup:
      image:
        tag: "6.1.2.5"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: ""
      itxaIntegration:
        image:
          tag: ""
        resourcesInit:
    test:
      image:
        tag: ""
    purge:
      enabled: true
      image:
        tag: "6.1.2.5"


# Storage Class Matrix - definition by Cloud Provider
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: "ibmc-file-gold"       # ReadOnlyMany  #FIXME need to define this value
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: "ocs-storagecluster-cephfs"
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: " gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: " managed-premium"
    rom: ""
    rwop: ""
