---
# Get values from Environment Variables
# -----------------------------------------------------------------------------
si_action: "{{ lookup('env', 'SI_ACTION') | default('install', true) }}"
si_instanceid: "{{ lookup('env', 'SI_INSTANCEID') }}"

env_db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') }}"
env_mq_namespace: "{{ lookup('env', 'MQ_NAMESPACE') | trim }}"

si_version: "{{ lookup('env', 'SI_VERSION') | default('6.2.0.2', true) }}"

si_licensetype: "{{ lookup('env', 'SI_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod
si_system_passphrase: "{{ lookup('env', 'SI_SYSTEM_PASSPHRASE') | default('passw0rd', true) }}"

si_skip_helm: "{{ lookup('env', 'SI_SKIP_HELM') | default(false, true) }}"

si_dbvendor: "{{ lookup('env', 'SI_DBVENDOR') }}"
si_dbhost: "{{ lookup('env', 'SI_DBHOST') }}"
si_dbport: "{{ lookup('env', 'SI_DBPORT') }}"
si_dbname: "{{ lookup('env', 'SI_DBNAME') }}"
si_dbuser: "{{ lookup('env', 'SI_DBUSER') }}"
si_dbpassword: "{{ lookup('env', 'SI_DBPASSWORD') }}"
si_oracle_useservicename: "{{ lookup('env', 'SI_ORACLESERVICENAME', default('false')) }}"

si_adminmailaddr: "{{ lookup('env', 'SI_ADMIN_MAILADDR') | default('admin@company.com', true) }}"
si_adminsmtphost: "{{ lookup('env', 'SI_ADMIN_SMTPHOST') | default('smtp.company.com', true) }}"

si_jmsuser: "{{ lookup('env', 'SI_JMS_USERNAME') }}"
si_jmspassword: "{{ lookup('env', 'SI_JMS_PASSWORD') }}"
si_jmskeystorepassword: "{{ lookup('env', 'SI_JMS_KEYSTORE_PASSWORD') }}"
si_jmstruststorepassword: "{{ lookup('env', 'SI_JMS_TRUSTSTORE_PASSWORD') }}"

si_libertykeystorepassword: "{{ lookup('env', 'SI_LIBERTY_KEYSTORE_PASSWORD') | default('changeit', true) }}"

si_actions_defaults:
  install:
    datasetup_enabled: "true"
    datasetup_upgrade: "false"
    env_upgradecompatibilityverified: "false"
  upgrade:
    datasetup_enabled: "true"
    datasetup_upgrade: "true"
    env_upgradecompatibilityverified: "true"
  prebuiltdb:
    datasetup_enabled: "false"
    datasetup_upgrade: "false"
    env_upgradecompatibilityverified: "false"

si_datasetup_enabled: "{{ lookup('env', 'SI_DATASETUP_ENABLED') | default(si_actions_defaults[si_action].datasetup_enabled, true) }}"
si_datasetup_upgrade: "{{ lookup('env', 'SI_DATASETUP_UPGRADE') | default(si_actions_defaults[si_action].datasetup_upgrade, true) }}"
si_env_timezone: "{{ lookup('env', 'SI_ENV_TIMEZONE') | default('UTC', true) }}"
si_env_upgradecompatibilityverified: "{{ lookup('env', 'SI_ENV_UPGRADE_COMPAT_VERIFIED') | default(si_actions_defaults[si_action].env_upgradecompatibilityverified, true) }}"
si_env_debugmode: "{{ lookup('env', 'SI_ENV_DEBUGMODE') | default('false', true) }}"

# Entitlement
# -----------------------------------------------------------------------------
entitled_registry: "cp.icr.io"
entitled_registry_user: cp
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Defaults for B2Bi instances.
# -----------------------------------------------------------------------------
my_workdir: /tmp

si_namespace: "sterling-b2bi-{{ si_instanceid }}-app"
si_db2_namespace: "sterling-b2bi-{{ si_instanceid }}-db2"
si_mq_namespace: "sterling-b2bi-{{ si_instanceid }}-mq"
si_registry_secret: si-ibm-registry
si_system_passphrase_secret: si-system-passphrase-secret
si_db_secret: si-db-secret
si_jms_secret: si-jms-secret
si_liberty_secret: si-liberty-secret

db2_namespace: ""
db2_secret: mydb2-secret
db2_id: mydb2

mq_namespace: ""
mq_secret: mymq-secret

# Helm Variables
# -----------------------------------------------------------------------------
si_helm:
  chart: "{{ my_workdir }}/ibm-b2bi-prod/"

# Sterling B2Bi Compatibility Matrix
# -----------------------------------------------------------------------------
compatibility_matrix:
  6.2.0.2:
    helm_version: "3.0.4"
    ocp_min_version: "4.14"
    k8s_min_version: "1.27"
    k8s_max_version: "1.29"
    global:
      image:
        tag: "6.2.0.2"
    resourcesInit:
      image:
        tag: "6.2.0.2"
    dataSetup:
      image:
        tag: "6.2.0.2"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: "10.1.2.0.20231130"
      itxaIntegration:
        image:
          repository: "cp.icr.io/cp/ibm-itxa/itxa-runtime"
          tag: "10.0.1.9-x86_64"
        resourcesInit:
          repository: "cp.icr.io/cp/ibm-itxa/itxa-resources"
          tag: "10.0.1.9-x86_64"
    test:
      image:
        tag: '1.1.65'
    purge:
      image:
        tag: "6.2.0.2"
    documentService:
      image:
        tag: 1.0.0.2
  6.2.0.1:
    helm_version: "3.0.1"
    ocp_min_version: "4.13"
    k8s_min_version: "1.26"
    k8s_max_version: "1.28"
    global:
      image:
        tag: "6.2.0.1"
    resourcesInit:
      image:
        tag: "6.2.0.1"
    dataSetup:
      image:
        tag: "6.2.0.1"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: "10.1.2.0.20231130"
      itxaIntegration:
        image:
          repository: "cp.icr.io/cp/ibm-itxa/itxa-runtime"
          tag: "10.0.1.8-x86_64"
        resourcesInit:
          repository: "cp.icr.io/cp/ibm-itxa/itxa-resources"
          tag: "10.0.1.8-x86_64"
    test:
      image:
        tag: '1.1.65'
    purge:
      image:
        tag: "6.2.0.1"
    documentService:
      image:
        tag: 1.0.0.1
  6.2.0.0:
    helm_version: "3.0.0"
    ocp_min_version: "4.12"
    k8s_min_version: "1.25"
    k8s_max_version: "1.27"
    global:
      image:
        tag: "6.2.0.0"
    resourcesInit:
      image:
        tag: "6.2.0.0"
    dataSetup:
      image:
        tag: "6.2.0.0"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: "10.1.1.1.20221116"
      itxaIntegration:
        image:
          repository: "cp.icr.io/cp/ibm-itxa-runtime"
          tag: "10.0.1.8"
        resourcesInit:
          repository: "cp.icr.io/cp/ibm-itxa-resources"
          tag: "10.0.1.8"
    test:
      image:
        tag: '1.1.62'
    purge:
      image:
        tag: "6.2.0.0"
    documentService:
      image:
        tag: 1.0.0.0


# Storage Class Matrix - definition by Cloud Provider
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: "ibmc-file-gold-gid"       # ReadOnlyMany  #FIXME need to define this value
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: "ocs-storagecluster-cephfs"
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: "gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: "managed-premium"
    rom: ""
    rwop: ""
  techzone:
    rwx: "managed-nfs-storage"
    rwx_nogid: "managed-nfs-storage"
    rwo: "managed-nfs-storage"
    rom: "managed-nfs-storage"
    rwop: "managed-nfs-storage"
  ibm-spectrum:
    rwx: "scale-cnsa"
    rwx_nogid: "scale-cnsa"
    rwo: "scale-cnsa"
    rom: "scale-cnsa"
    rwop: "scale-cnsa"
