---
- name: Check if Connect:Direct is already up and running
  ansible.builtin.shell: "ps -ef | grep cdpmgr | grep -v grep"
  changed_when: true
  register: __cd_running
  ignore_errors: true

- name: Check if Product already Installed?
  ansible.builtin.stat:
    path: "{{ __cd_install_path }}/ndm/cfg/{{ __cd_nodename }}/initparm.cfg"
  register: __cd_installed

- name: "Start IBM Connect:Direct"
  become_user: "{{ __cd_user }}"
  #environment:
  #  NDMAPICFG:   "{{ __cd_install_path }}/ndm/cfg/cliapi/ndmapi.cfg""
  #  PATH:        ""
  ansible.builtin.shell: "{{ __cd_install_path }}/ndm/bin/cdpmgr -i {{ __cd_install_path }}/ndm/cfg/__cd_nodename/initparm.cfg"
  register: cout
  changed_when: cout.rc == 0
  when: __cd_running.rc == 0
