---
# Create Certificate for Connect:Direct on Kubernetes
# -----------------------------------------------------------------------------
- name: Running OpenSSL command
  ansible.builtin.command:
    cmd: "openssl req -x509 -sha512 -days 3650 -newkey rsa:2048 -new -nodes -keyout {{ cd_cert_key }} -out {{ cd_cert_crt }} -subj '/CN={{ cd_nodename }}'"
  register: cout
  changed_when: false

- name: Concat C:D certificates
  ansible.builtin.shell:
    cmd: "cat {{ cd_cert_key }} {{ cd_cert_crt }} > {{ cd_cert_pem }}"
  changed_when: false
  when: cout.rc == 0

# - name: Generate OpenSSL certificate
#  ansible.builtin.openssl_certificate:
#    path: "{{ my_cert_certificatecrt }}"
#    privatekey_path: "{{ my_cert_privatekey }}"
#    privatekey_passphrase: "{{ cd_localCertPassphrase }}"
#    #subject: "/CN={{ cd_nodename }}""
#    #  commonName: "/{{ cd_nodename }}"
#    provider: selfsigned
#    #    signature_algorithms:
#    #      - sha512WithRSAEncryption
#    #   days:  3650
#    force: yes

# Create Certificate for Connect:Direct on Kubernetes
# CD install script only support extensions .crt, .pem and .cer
# -----------------------------------------------------------------------------
- name: Create or update Kubernetes secret with certificates files
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cd_deploy_cert_secret }}"
        namespace: "{{ cd_namespace }}"
      data:
        cdcert.pem: "{{ lookup('file', cd_cert_pem) | b64encode }}"
