---
- name: Define C:D helm chart values
  ansible.builtin.set_fact:
    cd_helm_values:
      licenseType: "{{ cd_license_type }}" # prod or no-prod
      cdArgs:
        nodeName: "{{ cd_nodename }}"
        crtName: "cdcert.pem"
      sum:
        enabled: "{{ 'y' if (cd_helm.sumEnabled == 1) else 'n' }}"
      persistence:
        useDynamicProvisioning: "{{ 'true' if (cd_use_dynamic_provisioning) else 'false' }}"
      secret:
        secretName: "{{ cd_secret }}"
        certSecretName: "{{ cd_cert_secret }}"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_workdir }}/mycd_values.yml"
    mode: "0640"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "Image Repository ................. {{ compatibility_matrix[cd_version].image_repository }}"
      - "Image Tag        ................. {{ compatibility_matrix[cd_version].image_tag }}"
      - "cd_helm_values   ................. {{ cd_helm_values }}"
      - "command: helm install --timeout {{ cd_helm.timeout }} --values={{ my_workdir }}/mycd_values.yml --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"

# - name: Run Helm delete command
#   shell: "helm delete --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"


- name: Run Helm install command
  ansible.builtin.shell: "helm install --timeout {{ cd_helm.timeout }} --values={{ my_workdir }}/mycd_values.yml --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"
# --timeout {{ cd_helm.timeout }}
# --wait

# # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
# - name: Deploy Connect:Direct chart from local path
#   kubernetes.core.helm:
#     name: "{{ cd_helm_release }}"
#     chart_ref: "{{ my_workdir }}/ibm-connect-direct/"
#     release_namespace: "{{ cd_namespace }}"
#     wait: True
#     timeout: "{{ cd_helm.timeout }}"
#     values_files:
#       - "{{ my_workdir }}/mycd_values.yml"

- name: "Lookup Connect:Direct Pod"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ cd_namespace }}"
    label_selectors:
      - release={{ cd_helm_release }}
    wait: true
    wait_sleep: 30
    wait_timeout: 300 # 5 mins until we give up waiting for the pod to get into the expected state
    wait_condition:
      type: Ready
      status: "True"
  register: cd_pod

- name: Configure facts
  ansible.builtin.set_fact:
    cd_pod_name: "{{ cd_pod.resources[0].metadata.name }}"

- name: "Pod Name"
  ansible.builtin.debug:
    msg:
      - "Pod name ............................... {{ cd_pod_name }}"
