---
- name: Define C:D helm chart values
  ansible.builtin.set_fact:
    cd_helm_values:
      licenseType: "{{ cd_licenseType }}" # prod or no-prod
      cdArgs:
        nodeName: "{{ cd_nodename }}"
        crtName: "cdcert.pem"
      sum:
        enabled: "{{ 'y' if (cd_helm.sumEnabled == 1) else 'n' }}"
      persistence:
        useDynamicProvisioning: "{{ 'true' if (cd_use_dynamic_provisioning) else 'false' }}"
      secret:
        secretName: "{{ cd_secret }}"
        certSecretName: "{{ cd_cert_secret }}"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_workdir }}/mycd_values.yml"

- name: Debug
  debug:
    msg:
      - "Image Repository ................. {{ compatibility_matrix[cd_version].image_repository }}"
      - "Image Tag        ................. {{ compatibility_matrix[cd_version].image_tag }}"
      - "cd_helm_values   ................. {{ cd_helm_values }}"
      - "command: helm install --timeout {{ cd_helm.timeout }} --values={{ my_workdir }}/mycd_values.yml --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"

# - name: Run Helm delete command
#   shell: "helm delete --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"


- name: Run Helm install command
  shell: "helm install --timeout {{ cd_helm.timeout }} --values={{ my_workdir }}/mycd_values.yml --namespace {{ cd_namespace }} {{ cd_helm_release }} {{ my_workdir }}/ibm-connect-direct/"
# --timeout {{ cd_helm.timeout }}
# --wait

