---
- name: Set fact helm file
  ansible.builtin.set_fact:
    my_helmfile: "{{ my_workdir }}/ibm-connect-direct-{{ compatibility_matrix[cd_version].helm_version }}.tgz"
    my_valuesfile: "{{ my_workdir }}/mycd_values-{{ my_serial }}.yml"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_valuesfile }}"
    mode: "0640"

- name: Helm Install command
  ansible.builtin.debug:
    msg:
      - "helm install --timeout 10m0s -f {{ my_valuesfile }} -n {{ cd_namespace }} s0 {{ my_helmfile }}"

- name: Run Helm install command
  ansible.builtin.command:
    cmd: "helm install --timeout 10m0s -f {{ my_valuesfile }} -n {{ cd_namespace }} s0 {{ my_helmfile }}"
  register: helm_cout
  changed_when: helm_cout.rc != 0
  when: not cd_skip_helm

- name: "Lookup Connect:Direct Pod"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ cd_namespace }}"
    label_selectors:
      - release=s0
    wait: true
    wait_sleep: 30
    wait_timeout: 300 # 5 mins until we give up waiting for the pod to get into the expected state
    wait_condition:
      type: Ready
      status: "True"
  register: cd_pod
  when: not cd_skip_helm

- name: Configure facts
  ansible.builtin.set_fact:
    cd_pod_name: "{{ cd_pod.resources[0].metadata.name }}"
  when: not cd_skip_helm

- name: IBM Sterling Connect:Direct Summary
  ansible.builtin.debug:
    msg:
      - "IBM Sterling Connect:Direct status .................. Ready!"
      - "Connect:Direct namespace ............................ {{ cd_namespace }}"
      - "Pod name ............................................ {{ cd_pod_name | default('') }}"
      - "For username and password check secret .............. {{ cd_deploy_secret }}'"
      - "helm install --timeout 10m0s -f {{ my_valuesfile }} -n {{ cd_namespace }} s0 {{ my_helmfile }}"
