---
- name: Define C:D helm chart values
  ansible.builtin.set_fact:
    cd_other_values:
      sum:
        enabled: "{{ 'y' if (cd_helm.sumEnabled == 1) else 'n' }}"
      persistence:
        useDynamicProvisioning: "{{ 'true' if (cd_use_dynamic_provisioning) else 'false' }}"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yml.j2"
    dest: "{{ my_workdir }}/mycd_values.yml"
    mode: "0640"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "Image Repository ................. {{ compatibility_matrix[cd_version].image_repository }}"
      - "Image Tag        ................. {{ compatibility_matrix[cd_version].image_tag }}"
      - "cd_other_values  ................. {{ cd_other_values }}"
      - "helm install --timeout {{ cd_helm.timeout }} -f {{ cd_helm.values_yaml }} -n {{ cd_namespace }} {{ cd_helm.release }} {{ cd_helm.chart }}"

- name: Run Helm install command
  ansible.builtin.shell:
    cmd: "helm install --timeout {{ cd_helm.timeout }} -f {{ cd_helm.values_yaml }} -n {{ cd_namespace }} {{ cd_helm.release }} {{ cd_helm.chart }}"
  register: helm_cout
  changed_when: helm_cout.rc != 0

# # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
# - name: Deploy Connect:Direct chart from local path
#   kubernetes.core.helm:
#     name: "{{ cd_helm_release }}"
#     chart_ref: "{{ cd_helm.chart }}"
#     release_namespace: "{{ cd_namespace }}"
#     wait: True
#     timeout: "{{ cd_helm.timeout }}"
#     values_files: "{{ cd_helm.values }}"

- name: "Lookup Connect:Direct Pod"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ cd_namespace }}"
    label_selectors:
      - release={{ cd_helm.release }}
    wait: true
    wait_sleep: 30
    wait_timeout: 300 # 5 mins until we give up waiting for the pod to get into the expected state
    wait_condition:
      type: Ready
      status: "True"
  register: cd_pod

- name: Configure facts
  ansible.builtin.set_fact:
    cd_pod_name: "{{ cd_pod.resources[0].metadata.name }}"

- name: "IBM Sterling Connect:Direct Summary:"
  ansible.builtin.debug:
    msg:
      - "IBM Sterling Connect:Direct status .................. Ready!"
      - "Connect:Direct namespace ............................ {{ cd_namespace }}"
      - "Pod name ............................................ {{ cd_pod_name }}"
      - "For username and password check secret .............. {{ cd_secret }}'"
