---
- name: "Fail if db2_namespace is not provided"
  ansible.builtin.assert:
    that:
      - db2_namespace is defined and db2_namespace != ""
    fail_msg: "db2_namespace property is required"

- name: "Install CCM,CCD ?"
  ansible.builtin.set_fact:
    scc_install_monitor: true
    scc_install_director: true
    scc_install: "CCM,CCD"
  when:
    - scc_products_upper.find('CCM') != -1
    - scc_products_upper.find('CCD') != -1

- name: "Install CCM ?"
  ansible.builtin.set_fact:
    scc_install_monitor: true
    scc_install_director: false
    scc_install: "CCM"
  when:
    - scc_install is not defined
    - scc_products_upper.find('CCM') != -1

- name: "Install CCD ?"
  ansible.builtin.set_fact:
    scc_install_monitor: false
    scc_install_director: true
    scc_install: "CCD"
  when:
    - scc_install is not defined
    - scc_products_upper.find('CCD') != -1

- name: Fail if neither CCM nor CCD found
  ansible.builtin.fail:
    msg: "Neither CCM nor CCD found in scc_products variable"
  when: scc_install is not defined
