- name: Install Nginx HTTP Server
  ansible.builtin.package:
    name: nginx
    # state: latest
    # allow_downgrade: true

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
