- name:                     Apply repository for CentOS
  template:
    src:                    "{{ __nginx_repo_template }}"
    dest:                   "{{ __nginx_repo_location }}"
  vars:
    dist:                   "centos"
    version:                "{{ ansible_distribution_major_version }}"
  when:
   - ansible_distribution == "CentOS"

- name:                     Apply repository for RHEL
  template:
    src:                    "{{ __nginx_repo_template }}"
    dest:                   "{{ __nginx_repo_location }}"
  vars:
    dist:                   "rhel"
    version:                "{{ ansible_distribution_major_version }}"
  when:
   - ansible_distribution == "RedHat"
   - ansible_distribution_major_version == "7"

- name:                     Disable SELinux
  selinux:
    state:                  disabled
  ignore_errors:            true
  notify:                   reboot

#  when:
#    - ansible_os_family == "RedHat"
#    - ansible_distribution_major_version == "8"