- name: Apply repository for CentOS
  ansible.builtin.template:
    src: "{{ __nginx_repo_template }}"
    dest: "{{ __nginx_repo_location }}"
  vars:
    dist: "centos"
    version: "{{ ansible_distribution_major_version }}"
  when:
    - ansible_distribution == "CentOS"

- name: Apply repository for RHEL
  ansible.builtin.template:
    src: "{{ __nginx_repo_template }}"
    dest: "{{ __nginx_repo_location }}"
  vars:
    dist: "rhel"
    version: "{{ ansible_distribution_major_version }}"
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  failed_when: false
  notify: reboot
#  when:
#    - ansible_os_family == "RedHat"
#    - ansible_distribution_major_version == "8"
