---
kafka_namespace: "{{ lookup('env', 'KAFKA_NAMESPACE') | default('sterling-kafka-strimzi', true) }}"
kowl_namespace: "{{ lookup('env', 'KOWL_NAMESPACE') | default('sterling-kowl', true) }}"

kafka_user_name: "{{ lookup('env', 'KAFKA_USER_NAME') | default('siuser', true) }}"

kafka_brokers: "sterling-kfk-kafka-brokers.{{ kafka_namespace }}.svc.cluster.local:9092"

kowl_image: quay.io/cloudhut/kowl:master
