---
# - name: Check for required environment variables
#   ansible.builtin.assert:
#     that:
#       # NAMESPACE
#       - lookup('env', 'KAFKA_NAMESPACE') != ""
#     fail_msg: "One or more required environment variables are not defined"


# 1. Fail if required parameters are not set
# -----------------------------------------------------------------------------
- name: "Fail if required properties have not been provided"
  ansible.builtin.assert:
    that:
      - kafka_namespace is defined and kafka_namespace != ""
      - kowl_namespace is defined and kowl_namespace != ""
    fail_msg: "One or more required properties have not been set"
