---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ kowl_namespace }}"
        labels:
          name: kowl
  register: cout

# Create Secrets
# -----------------------------------------------------------------------------
- name: Create Secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: kowl-secret
        namespace: "{{ kowl_namespace }}"
        labels:
          app: kowl
      type: Opaque
      stringData:
        KAFKA_USER_NAME: "{{ kafka_user_name }}"

# # Create ServiceAccount
# -----------------------------------------------------------------------------
- name: Create Service Account
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kowl-sa
        namespace: "{{ kowl_namespace }}"

# Create Role Binding
# -----------------------------------------------------------------------------
- name: Create Role Binding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: 'kowl-anyuid'
        namespace: "{{ kowl_namespace }}"
        labels:
          app: kowl
      subjects:
        - kind: ServiceAccount
          name: kowl-sa
          namespace: "{{ kowl_namespace }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: 'system:openshift:scc:anyuid'
