---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for Sterling Control Center"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ scc_namespace }}"
  register: cout

# Create Secrets for IBM Registry
# -----------------------------------------------------------------------------
- name: Create secret content '{{ si_registry_secret }}'
  no_log: false
  vars:
    entitled_auth_str: "cp:{{ entitled_registry_key }}"
    entitled_auth_b64: "{{ entitled_auth_str | b64encode }}"
    content:
      - '{"auths":{"cp.icr.io":{"username":"cp","password":"{{ entitled_registry_key }}",'
      - '"email":"cp","auth":"{{ entitled_auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate secret '{{ scc_registry_secret }}'"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ scc_registry_secret }}"
        namespace: "{{ scc_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: ibm_registry_secret_cout

# Create Certificate for IBM Control Center
# -----------------------------------------------------------------------------
- name: Create Java KeyStore
  ansible.builtin.command:
    cmd: >-
      keytool -genkeypair -keyalg RSA -keysize 2048 -validity 3650 -alias {{ scc_keyalias }}
      -keystore {{ scc_keystore }} -storepass {{ scc_keystore_password }}
      -keypass {{ scc_keystore_password }} -dname "CN={{ scc_name }}, OU=Sterling Data Exchange Product Management, O=IBM, L=Austin, ST=Texas, C=United States"
  changed_when: true

- name: Export key
  ansible.builtin.command:
    cmd: >-
      keytool -export -alias {{ scc_keyalias }}
      -keystore {{ scc_keystore }} -storepass {{ scc_keystore_password }}
      -rfc -file {{ scc_cert_crt }}
  changed_when: true

- name: Create Java TrustStore
  ansible.builtin.command:
    cmd: >-
      keytool -import -trustcacerts -noprompt -alias {{ scc_keyalias }}
      -file {{ scc_cert_crt }}
      -keystore {{ scc_truststore }} -storepass {{ scc_truststore_password }}
  changed_when: true

- name: Create or update Kubernetes secret with certificates files
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ scc_cert_secret }}"
        namespace: "{{ scc_namespace }}"
      data:
        keystore: "{{ lookup('file', scc_keystore) | b64encode }}"
        truststore: "{{ lookup('file', scc_truststore) | b64encode }}"

# For TLS certificate if ingress will be used
# This secret will be created only if Kubernetes Ingress resource needs to be created. Create Kubernetes TLS secret with following command:
# oc create secret tls ibm-sccm-tls --key=<key file path> --cert=<cert file path> -n ibm-scc
