---
- name: "Cleanup directories and files"
  ansible.builtin.file:
    path: "{{ my_workdir }}/ibm-sccm-{{ compatibility_matrix[scc_version].helm_version }}"
    state: absent
  with_items:
    - "{{ my_workdir }}/ibm-sccm-{{ compatibility_matrix[scc_version].helm_version  }}.tgz"
    - "{{ my_workdir }}/ibm-sccm"
    - "{{ my_workdir }}/myscc_values.yml"

- name: "Download Helm chart"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-sccm-{{ compatibility_matrix[scc_version].helm_version }}.tgz"
    dest: "{{ my_workdir }}/ibm-sccm-{{ compatibility_matrix[scc_version].helm_version }}.tgz"
  register: download_cout
  until: download_cout is succeeded
  retries: 3

- name: "Extract Helm chart"
  ansible.builtin.command: "tar -xzvf {{ my_workdir }}/ibm-sccm-{{ compatibility_matrix[scc_version].helm_version }}.tgz -C {{ my_workdir }}"
  register: untar_cout
  changed_when: ( untar_cout.rc == 0)


# - name: Download Chart using  ibm-sccm and repo_url
#   kubernetes.core.helm_pull:
#     chart_ref: ibm-sccm
#     repo_url: "https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-sccm-{{ compatibility_matrix[ scc_version ].helm_version  }}.tgz"
#     untar_chart: yes
#     destination: "{{ my_workdir }}/ibm-sccm"
# repo_url: https://github.com/grafana/helm-charts/releases/download/grafana-5.6.0/grafana-5.6.0.tgz

# Creating a Role Based Access Control (RBAC)
# -----------------------------------------------------------------------------
- name: "Creating a Role Based Access Control (RBAC)"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/default_sa_rbac.yml.j2') }}"


# # Creating a Custom PodSecurityPolicy - Removed in Kubernetes v1.25
# # -----------------------------------------------------------------------------
# - name: "Creating a Custom PodSecurityPolicy"
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'templates/custom_podsecplcy.yml.j2') }}"

# - name: "Creating a Custom Role and Role Binding for the custom PodSecurityPolicy"
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'templates/custom_podsecplcy_rbac.yml.j2') }}"

# # Creating a Custom SecurityContextConstraints definition - Removed in Kubernetes v1.25
# # -----------------------------------------------------------------------------
# - name: "Creating a Custom SecurityContextConstraints"
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'templates/custom_secctxtcons.yml.j2') }}"

# - name: "Creating a Custom Role and Role Binding for the custom PodSecurityPolicy"
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', 'templates/custom_podsecplcy_rbac.yml.j2') }}"