---
# Get Information from db2_namespace
# -----------------------------------------------------------------------------
- name: "Lookup Secrets from db2_namespace if provided"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ db2_secret }}"
    namespace: "{{ db2_namespace }}"
  register: db_secret_cout
  when: db2_namespace is defined and db2_namespace != ""

- name: "Lookup Service from db2_namespace if provided"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: "{{ db2_id }}-ci"
    namespace: "{{ db2_namespace }}"
  register: db_svc_cout
  when: db2_namespace is defined and db2_namespace != ""

- name: Debug
  ansible.builtin.debug:
    msg:
      - "db_svc_cout ................. {{ db_svc_cout }}"

# jdbc_url: "jdbc:db2://c-{{db2_instance_name | lower}}-db2u-engn-svc.{{ db2_namespace }}.svc:{{db2_tls_serviceport}}/{{db2_dbname}}:sslConnection=true;sslVersion={{ tls_version }};"
- name: Set Facts for Database Configuration from db2_namespace
#  no_log: true
  ansible.builtin.set_fact:
    scc_dbvendor: "DB2"
    scc_dbhost: "{{ db2_id }}-ci.{{ db2_namespace }}.svc.cluster.local"
    scc_dbport: "{{ db_svc_cout.resources[0].spec.ports[0].port }}"
    scc_dbname: "SCCM"
    scc_dbuser: "db2inst1"
    scc_dbpassword: "{{ db_secret_cout.resources[0].data.DB2INST1_PASSWORD | b64decode }}"
  when:
    - db2_namespace is defined and db2_namespace != ""
    - db_secret_cout is defined and db_secret_cout != ""
    - db_svc_cout is defined and db_svc_cout != ""

- name: Set Facts for Database Configuration when is Oracle
#  no_log: true
  ansible.builtin.set_fact:
    scc_dbdrivers: "/app/CC/conf/db2jcc4.jar,/app/CC/conf/db2jcc_license_cu.jar"
    scc_mssqlglobal: "false"
    scc_oracle_racorscan: ""
  when:
    - scc_dbvendor is defined and scc_dbvendor == "DB2"

# # Followings are DB drivers available inside jdbc driver container
# 1. /ibm/scc/resoures/dbdrivers/db2/luw/v11.5/v4.32.28/db2jcc_license_cu.jar
# 2. /ibm/scc/resoures/dbdrivers/db2/luw/v11.5/v4.32.28/db2jcc4.jar
# 3. /ibm/scc/resoures/dbdrivers/db2/luw/v11.5/v4.33.31/db2jcc_license_cu.jar
# 4. /ibm/scc/resoures/dbdrivers/db2/luw/v11.5/v4.33.31/db2jcc4.jar
# 5. /ibm/scc/resoures/dbdrivers/mssql/v2017/mssql-jdbc-11.2.3.jre17.jar
# 6. /ibm/scc/resoures/dbdrivers/mssql/v2017/mssql-jdbc-12.6.1.jre11.jar
# 7. /ibm/scc/resoures/dbdrivers/mssql/v2017/mssql-jdbc-11.2.3.jre8.jar
# 8. /ibm/scc/resoures/dbdrivers/mssql/v2017/mssql-jdbc-12.6.1.jre8.jar
# 9. /ibm/scc/resoures/dbdrivers/mssql/v2019/mssql-jdbc-11.2.3.jre17.jar
# 10./ibm/scc/resoures/dbdrivers/mssql/v2019/mssql-jdbc-12.6.1.jre11.jar
# 11./ibm/scc/resoures/dbdrivers/mssql/v2019/mssql-jdbc-12.6.1.jre8.jar
# 12./ibm/scc/resoures/dbdrivers/mssql/v2019/mssql-jdbc-11.2.3.jre8.jar
# 13./ibm/scc/resoures/dbdrivers/oracle/v19c/ojdbc10.jar
# 14./ibm/scc/resoures/dbdrivers/oracle/v19c/ojdbc8.jar
# 15./ibm/scc/resoures/dbdrivers/oracle/v21c/ojdbc11.jar
# 16./ibm/scc/resoures/dbdrivers/oracle/v21c/ojdbc8.jar
- name: Set Facts for Database Configuration when is Oracle
#  no_log: true
  ansible.builtin.set_fact:
    scc_dbdrivers: "/app/CC/conf/ojdbc8.jar"
    scc_mssqlglobal: "false"
    scc_oracle_racorscan: ""
  when:
    - scc_dbvendor is defined and scc_dbvendor == "Oracle"

- name: Set Facts for Database Configuration when is Oracle
#  no_log: true
  ansible.builtin.set_fact:
    scc_dbdrivers: "/app/CC/conf/mssql-jdbc-12.6.1.jre8.jar"
    scc_mssqlglobal: "false"
    scc_oracle_racorscan: ""
  when:
    - scc_dbvendor is defined and scc_dbvendor == "SQLServer"

# Debug
# -----------------------------------------------------------------------------
- name: Debug
  ansible.builtin.debug:
    msg:
      - "DB Vendor ................. {{ scc_dbvendor }}"
      - "DB Host   ................. {{ scc_dbhost }}"
      - "DB Port   ................. {{ scc_dbport }}"
      - "DB Name   ................. {{ scc_dbname }}"
      - "DB User   ................. {{ scc_dbuser }}"
      - "DB Password ............... {{ scc_dbpassword }}"

- name: "Fail if Database Information is not provided"
  ansible.builtin.assert:
    that:
      - scc_dbvendor is defined and scc_dbvendor != ""
      - scc_dbdrivers is defined and scc_dbdrivers != ""
      - scc_dbhost is defined and scc_dbhost != ""
      - scc_dbport is defined and scc_dbport != ""
      - scc_dbname is defined and scc_dbname != ""
      - scc_dbuser is defined and scc_dbuser != ""
      - scc_dbpassword is defined and scc_dbpassword != ""
    fail_msg: "Database Properties are required"
