---
# Debug
# -----------------------------------------------------------------------------
# Get Information from mq_namespace
# -----------------------------------------------------------------------------
- name: "Lookup Secrets from mq_namespace if provided"
#  no_log: true
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ mq_secret }}"
    namespace: "{{ mq_namespace }}"
  register: jms_secret_cout
  when: mq_namespace is defined and mq_namespace != ""

- name: "Lookup Service from mq_namespace if provided"
#  no_log: true
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: "mq-data"
    namespace: "{{ mq_namespace }}"
  register: jms_svc_cout
  when: mq_namespace is defined and mq_namespace != ""

- name: Set Facts for JMS Configuration from mq_namespace
#  no_log: true
  ansible.builtin.set_fact:
    scc_jmsuser: "app"
    scc_jmsvendor: "IBMMQ"
    scc_jmsconnectionfactory: "com.ibm.mq.jms.MQQueueConnectionFactory"
    scc_jmsqueuename: "DEV.QUEUE.1"
    scc_jmschannel: "DEV.APP.SVRCONN"
    scc_jmsenablessl: "false"
    scc_jmspassword: "{{ jms_secret_cout.resources[0].data.appPassword | b64decode }}"
    # scc_jmskeystorepassword: "{{ jms_secret_cout.resources[0].data.JMS_KEYSTORE_PASSWORD | b64decode }}"
    # scc_jmstruststorepassword: "{{ jms_secret_cout.resources[0].data.JMS_TRUSTSTORE_PASSWORD | b64decode }}"
    scc_jmshost: "mq-data.{{ mq_namespace }}.svc.cluster.local"
    scc_jmsport: "{{ jms_svc_cout.resources[0].spec.ports[0].port }}"
    scc_jmsconnectionnamelist: "mq-data.{{ mq_namespace }}.svc.cluster.local({{ jms_svc_cout.resources[0].spec.ports[0].port }})"
  when:
    - mq_namespace is defined and mq_namespace != ""
    - jms_secret_cout is defined and jms_secret_cout != ""
    - jms_svc_cout is defined and jms_svc_cout != ""

- name: Debug
  ansible.builtin.debug:
    msg:
      - "JMS User     ................. {{ scc_jmsuser }}"
      - "JMS Password ................. {{ scc_jmspassword }}"
      - "JMS keypw    ................. {{ scc_jmskeystorepassword }}"
      - "JMS trustpw  ................. {{ scc_jmstruststorepassword }}"

- name: "Fail if Database Information is not provided"
  ansible.builtin.assert:
    that:
      - scc_jmsuser is defined and scc_jmsuser != ""
      - scc_jmspassword is defined and scc_jmspassword != ""
    fail_msg: "JMS Queue Properties are required"

- name: "Generate secret '{{ scc_jms_secret }}'"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ scc_jms_secret }}"
        namespace: "{{ scc_namespace }}"
      data:
        JMS_USERNAME: "{{ scc_jmsuser | b64encode }}"
        JMS_PASSWORD: "{{ scc_jmspassword | b64encode }}"
        # JMS_KEYSTORE_PASSWORD: "{{ scc_jmskeystorepassword | b64encode }}"
        # JMS_TRUSTSTORE_PASSWORD: "{{ scc_jmstruststorepassword | b64encode }}"
  register: scc_jms_secret_cout
