---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets for Sterling Control Center
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Applying Pod Security
  ansible.builtin.include_tasks: 03_apply_pod_security.yml

- name: Define Storage for data persistence
  ansible.builtin.include_tasks: 04_define_storage.yml

- name: Setup JDBC Configuration
  ansible.builtin.include_tasks: 05_define_database.yml

# - name: Setup JMS Queue Configuration
#   ansible.builtin.include_tasks: 06_define_jmsqueue.yml

- name: Install Sterling Control Center using Helm Chart
  ansible.builtin.include_tasks: 07_install_scc.yml
