---
# Get values from Environment Variables
# -----------------------------------------------------------------------------
sccm_instanceid: "{{ lookup('env', 'SCCM_INSTANCEID') }}"
sccm_domain: "{{ lookup('env', 'SCCM_DOMAIN') }}"
env_db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') }}"

sccm_licensetype: "{{ lookup('env', ' SCCM_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod
sccm_system_passphrase: "{{ lookup('env', ' SCCM_SYSTEM_PASSPHRASE') | default('passwOrd', true) }}"

sccm_admin: "{{ lookup('env', 'SCCM_ADMIN') | default('admin', true) }}"
sccm_admin_password: "{{ lookup('env', ' SCCM_ADMIN_PASSWORD') | default('passwOrd', true) }}"
sccm_truststore_password: "{{ lookup('env', ' SCCM_TRUSTSTORE_PASSWORD') | default('changeit', true) }}"
sccm_keystore_password: "{{ lookup('env', ' SCCM_KEYSTORE_PASSWORD') | default('changeit', true) }}"
sccm_userkey: "{{ lookup('env', ' SCCM_EMAIL_PASSWORD') | default('passwOrd', true) }}"


sccm_dbvendor: "{{ lookup('env', ' SCCM_DBVENDOR') }}"
sccm_dbhost: "{{ lookup('env', ' SCCM_DBHOST') }}"
sccm_dbport: "{{ lookup('env', ' SCCM_DBPORT') }}"
sccm_dbname: "{{ lookup('env', ' SCCM_DBNAME') }}"
sccm_dbuser: "{{ lookup('env', ' SCCM_DBUSER') }}"
sccm_dbpassword: "{{ lookup('env', ' SCCM_DBPASSWORD') }}"

sccm_emailhostname: "{{ lookup('env', ' SCCM_SMTPHOST') | default('smtp.company.com', true) }}"
sccm_emailport: "{{ lookup('env', ' SCCM_SMTPPORT') | default('25', true) }}"
sccm_emailuser: "{{ sccm_admin }}"
sccm_emailrespond: "{{ lookup('env', ' SCCM_EMAIL_RESPOND') | default('noreply@company.com', true) }}"
sccm_ccadmin_emailaddress: "{{ lookup('env', ' SCCM_ADMIN_MAILADDR') | default('admin@company.com', true) }}"
sccm_emailpassword: "{{ lookup('env', ' SCCM_EMAIL_PASSWORD') | default('passwOrd', true) }}"
sccm_smtp_tlsenabled: "{{ lookup('env', ' SCCM_SMTP_TLSENABLED') | default('false', true) }}"

sccm_jmsuser: "{{ lookup('env', ' SCCM_JMS_USERNAME') }}"
sccm_jmspassword: "{{ lookup('env', ' SCCM_JMS_PASSWORD') }}"
sccm_jmskeystorepassword: "{{ lookup('env', ' SCCM_JMS_KEYSTORE_PASSWORD') }}"
sccm_jmstruststorepassword: "{{ lookup('env', ' SCCM_JMS_TRUSTSTORE_PASSWORD') }}"

sccm_timezone: "{{ lookup('env', ' SCCM_TIMEZONE') | default('America/New_York', true) }}"
sccm_dashboard: "true" # for ibm cloud environment
sccm_oc_route: "true" # applicable for openshift environment for accessing UI 

# Entitlement
# -----------------------------------------------------------------------------
entitled_registry: "cp.icr.io"
entitled_registry_user: cp
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Defaults for B2Bi instances.
# -----------------------------------------------------------------------------
my_workdir: /tmp

sccm_namespace: "sterling-b2bi-{{ sccm_instanceid }}-app"
sccm_db2_namespace: "sterling-b2bi-{{ sccm_instanceid }}-db2"
sccm_version: "6.2.0.0"

sccm_registry_secret: ibm-registry-secret
sccm_secret: ibm-sccm-secret
sccm_cert_secret: ibm-sccm-certs-secret
sccm_cert_crt: "{{ my_workdir }}/cdcert.crt"  # CD install script only support extensions .crt, .pem and .cer
sccm_cert_key: "{{ my_workdir }}/cdkey.pem"
sccm_cert_pem: "{{ my_workdir }}/cdcert.pem"


sccm_jms_secret: si-jms-secret
sccm_liberty_secret: si-liberty-secret

sccm_asccm_host: "asi.{{ sccm_instanceid }}.{{ sccm_domain }}"
sccm_ac_host: "ac.{{ sccm_instanceid }}.{{ sccm_domain }}"
sccm_api_host: "api.{{ sccm_instanceid }}.{{ sccm_domain }}"

db2_namespace: ""
db2_secret: mydb2-secret
db2_id: mydb2

# Helm Variables
# -----------------------------------------------------------------------------
sccm_helm:
  release: s0
  timeout: "120m0s"
  values_yaml: "{{ my_workdir }}/mysccm_values.yml"
  chart: "{{ my_workdir }}/ibm-b2bi-prod/"

# Sterling B2Bi Compatibility Matrix
# -----------------------------------------------------------------------------
compatibility_matrix:
  6.3.1.0_iFix01_2024-02-01:
    helm_version: "3.1.1"
    image_tag: "6.3.1.0_iFix01_2024-02-01"
    copy_resources_tag: "6.2.1.0_ifix08_2022-09-16"
  6.3.1.0_2023-12-15:
    helm_version: "3.1.0"
    image_tag: "6.3.1.0_2023-12-15"
    copy_resources_tag: "6.2.1.0_ifix08_2022-09-16"


# Storage Class Matrix - definition by Cloud Provider
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: "ibmc-file-gold-gid"       # ReadOnlyMany  #FIXME need to define this value
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: "ocs-storagecluster-cephfs"
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: " gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: " managed-premium"
    rom: ""
    rwop: ""
