---
# Get values from Environment Variables
# -----------------------------------------------------------------------------
sccm_instanceid: "{{ lookup('env', 'SCCM_INSTANCEID') }}"
sccm_domain: "{{ lookup('env', 'SCCM_DOMAIN') }}"
env_db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') }}"

sccm_licenseType: "{{ lookup('env', 'SI_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod
sccm_system_passphrase: "{{ lookup('env', 'SI_SYSTEM_PASSPHRASE') | default('passwOrd', true) }}"

sccm_dbvendor: "{{ lookup('env', 'SI_DBVENDOR') }}"
sccm_dbhost: "{{ lookup('env', 'SI_DBHOST') }}"
sccm_dbport: "{{ lookup('env', 'SI_DBPORT') }}"
sccm_dbname: "{{ lookup('env', 'SI_DBNAME') }}"
sccm_dbuser: "{{ lookup('env', 'SI_DBUSER') }}"
sccm_dbpassword: "{{ lookup('env', 'SI_DBPASSWORD') }}"
sccm_oracleUseServiceName: "{{ lookup('env', 'SI_ORACLESERVICENAME', default('false')) }}"

sccm_adminmailaddr: "{{ lookup('env', 'SI_ADMIN_MAILADDR') | default('admin@company.com', true) }}"
sccm_adminsmtphost: "{{ lookup('env', 'SI_ADMIN_SMTPHOST') | default('smtp.company.com', true) }}"

sccm_jmsuser: "{{ lookup('env', 'SI_JMS_USERNAME') }}"
sccm_jmspassword: "{{ lookup('env', 'SI_JMS_PASSWORD') }}"
sccm_jmskeystorepassword: "{{ lookup('env', 'SI_JMS_KEYSTORE_PASSWORD') }}"
sccm_jmstruststorepassword: "{{ lookup('env', 'SI_JMS_TRUSTSTORE_PASSWORD') }}"

sccm_libertykeystorepassword: "{{ lookup('env', 'SI_LIBERTY_KEYSTORE_PASSWORD') | default('changeit', true) }}"

# Entitlement
# -----------------------------------------------------------------------------
entitled_registry: "cp.icr.io"
entitled_registry_user: cp
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Defaults for B2Bi instances.
# -----------------------------------------------------------------------------
my_workdir: /tmp

sccm_namespace: "sterling-b2bi-{{ sccm_instanceid }}-app"
sccm_db2_namespace: "sterling-b2bi-{{ sccm_instanceid }}-db2"
sccm_version: "6.2.0.0"
sccm_registry_secret: si-ibm-registry
sccm_system_passphrase_secret: si-system-passphrase-secret
sccm_db_secret: si-db-secret
sccm_jms_secret: si-jms-secret
sccm_liberty_secret: si-liberty-secret
sccm_helm_release: s0
sccm_helm_timeout: "120m0s"
sccm_asccm_host: "asi.{{ sccm_instanceid }}.{{ sccm_domain }}"
sccm_ac_host: "ac.{{ sccm_instanceid }}.{{ sccm_domain }}"
sccm_api_host: "api.{{ sccm_instanceid }}.{{ sccm_domain }}"

db2_namespace: ""
db2_secret: mydb2-secret
db2_id: mydb2

# Sterling B2Bi Compatibility Matrix
# -----------------------------------------------------------------------------
compatibility_matrix:
  6.2.0.0:
    helm_version: "3.0.0"
    global:
      image:
        tag: "6.2.0.0"
    resourcesInit:
      image:
        tag: "6.2.0.0"
    dataSetup:
      image:
        tag: "6.2.0.0"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: "10.1.1.1.20221116"
      itxaIntegration:
        image:
          tag: "10.0.1.8"
        resourcesInit:
          tag: "10.0.1.8"
    test:
      image:
        tag: '1.1.62'
    purge:
      image:
        tag: "6.2.0.0"
    documentService:
      image:
        tag: 1.0.0.0
  6.1.2.5:
    helm_version: "2.1.6"
    global:
      image:
        tag: "6.1.2.5"
    resourcesInit:
      image:
        tag: "6.1.2.5"
    dataSetup:
      image:
        tag: "6.1.2.5"
    integrations:
      seasIntegration:
        seasVersion: "1.0"
      itxIntegration:
        image:
          tag: ""
      itxaIntegration:
        image:
          tag: ""
        resourcesInit:
    test:
      image:
        tag: ""
    purge:
      enabled: true
      image:
        tag: "6.1.2.5"


# Storage Class Matrix - definition by Cloud Provider
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: "ibmc-file-gold-gid"       # ReadOnlyMany  #FIXME need to define this value
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: "ocs-storagecluster-cephfs"
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: " gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: " managed-premium"
    rom: ""
    rwop: ""
