---
- name: Define Facts
  ansible.builtin.set_fact:
    policy_name: "http-policy-01"
    netmap_name: "http-netmap-01"
    adapter_name: "http-adapter-01"
    adapter_listen_port: "25000"

- name: Define Facts
  ansible.builtin.set_fact:
    policy_xml: |
      <httpPolicyDef>
        <authenticationType>basic</authenticationType>
        <blockCommonExploits>true</blockCommonExploits>
        <commonExploitStrings>"--", "'", "%00"</commonExploitStrings>
        <description>HTTP Policy</description>
        <eaAuthProfile></eaAuthProfile>
        <eaCertProfile></eaCertProfile>
        <eaCertValidation>false</eaCertValidation>
        <forceToUnlock>false</forceToUnlock>
        <name>{{ policy_name }}</name>
        <protocol>http</protocol>
        <protocolValidationOn>true</protocolValidationOn>
        <status>locked</status>
        <userAuthentication>none</userAuthentication>
        <userMapping>passthru</userMapping>
      </httpPolicyDef>
    netmap_xml: |
      {
        "name": "http-passthru-nm",
        "description": "HTTP Pass-Through netmap",
        "protocol": "http"
      }
    adapter_xml: |
      {
        "name": "sfg-adapter-01",
        "listenPort": "30140",
        "netmap": "http-passthru-nm",
            "engineName": "ssp-engine-01",
      }

- name: Create Policy HTTP
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/policy/createPolicy
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ policy_xml }}"
    status_code: 200
    validate_certs: false
  when: ssp_cfg.http.policy
  register: http_plc_cout

- name: Create Netmap HTTP
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/netmap/createNetmap
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ netmap_xml }}"
    status_code: 200
    validate_certs: false
  when: ssp_cfg.http.netmap
  register: http_np_cout

- name: Create Adapter HTTP
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/adapter/createAdapter
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ adapter_xml }}"
    status_code: 200
    validate_certs: false
  when: ssp_cfg.http.adapter
  register: http_adp_cout
