---
- name: Define Facts
  ansible.builtin.set_fact:
    config_name: "MyFG"
    create_policy: "{{ ssp_config_http.create_policy }}"
    create_netmap: "{{ ssp_config_http.create_netmap }}"
    create_adapter: "{{ ssp_config_http.create_adapter }}"
    policy_xml: |
      <httpPolicyDef>
        <name>myfg-policy-test</name>
        <description><![CDATA[]]></description>
        <authenticationType>basic</authenticationType>
        <blockCommonExploits>true</blockCommonExploits>
        <commonExploitStrings>"--", "'","%00"</commonExploitStrings>
        <eaCertValidation>false</eaCertValidation>
        <protocol>http</protocol>
        <protocolValidationOn>true</protocolValidationOn>
        <status></status>
        <userAuthentication>none</userAuthentication>
        <userMapping>passthru</userMapping>
      </httpPolicyDef>
    netmap_xml: |
      <netmapDef>
        <description><![CDATA[HttpDesc]]></description>
        <inboundNodes>
          <inboundNodeDef>
            <description><![CDATA[InboundDesc]]></description>
            <logLevel>NONE</logLevel>
            <name>InboundNode</name>
            <peerAddressPattern>*</peerAddressPattern>
            <policyId>Http_Policy_test</policyId>
            <secureConnection>false</secureConnection>
          </inboundNodeDef>
        </inboundNodes>
        <name>Http_Netmap_test</name>
        <outboundNodes>
          <outboundNodeDef>
            <addresses>
              <address>
                <nodeName>OutboundNode</nodeName>
                <host>1.1.1.1</host>
                <port>3333</port>
              </address>
            </addresses>
            <description><![CDATA[OutboundDesc]]></description>
            <logLevel>NONE</logLevel>
            <name>Outbound</name>
            <secureConnection>false</secureConnection>
            <validDestination>1.1.1.1</validDestination>
            <validDestinationPort>3333</validDestinationPort>
          </outboundNodeDef>
        </outboundNodes>
        <protocol>http</protocol>
        <status></status>
      </netmapDef>
    adapter_xml: |
      <httpAdapterDef>
        <description><![CDATA[HttpDesc]]></description>
        <engines></engines>
        <listenPort>2222</listenPort>
        <logLevel>ERROR</logLevel>
        <maxSessions>150</maxSessions>
        <name>Http_Adapter_test</name>
        <netmap>Http_Netmap_test</netmap>
        <netmapKey>Outbound</netmapKey>
        <htmlUrlRewrite>false</htmlUrlRewrite>
        <properties>
          <property>
            <name>html.rewrite.threads</name>
            <value>10</value>
          </property>
          <property>
            <name>http.commands.allowed</name>
            <value></value>
          </property>
          <property>
            <name>http.commands.prohibited</name>
            <value></value>
          </property>
          <property>
            <name>httpMaxHeaderFieldLength</name>
            <value>8192</value>
          </property>
          <property>
            <name>httpMaxNumHeaderFields</name>
            <value>1024</value>
          </property>
          <property>
            <name>max.ps.client.threads</name>
            <value>10</value>
          </property>
          <property>
            <name>max.ps.server.threads</name>
            <value>10</value>
          </property>
        </properties>
        <protocol>http</protocol>
        <sessionTimeout>3</sessionTimeout>
        <ssoConfig></ssoConfig>
        <standardRoute>Outbound</standardRoute>
        <status></status>
        <urlRoutingType>standardRouting</urlRoutingType>
      </httpAdapterDef>

# POST https://localhost:8443/sspcmrest/sspcm/rest/policy/createPolicy
- name: Create Policy {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/policy/createPolicy
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ policy_xml }}"
    status_code: 200
    validate_certs: false
  when: create_policy
  register: policy_result

- name: Create Netmap {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/netmap/createNetmap
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ netmap_xml }}"
    status_code: 200
    validate_certs: false
  when: create_netmap
  register: netmap_result

- name: Create Adapter {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/adapter/createAdapter
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ adapter_xml }}"
    status_code: 200
    validate_certs: false
  when: create_adapter
  register: adapter_result
