---
- name: Define Facts
  ansible.builtin.set_fact:
    config_name: "C:D"
    create_policy: "{{ ssp_config_cd.create_policy }}"
    create_netmap: "{{ ssp_config_cd.create_netmap }}"
    create_adapter: "{{ ssp_config_cd.create_adapter }}"
    policy_xml: |
        <cdPolicy>
          <name>cd-policy-test</name>
          <description><![CDATA[]]></description>
        </cdPolicy>
    netmap_xml: |
      <netmap>
        <name>cd-netmap-01</name>
        <description><![CDATA[CD Netmap 01]]></description>
        <entries>
          <entry>
            <source>source1</source>
            <destination>destination1</destination>
          </entry>
          <entry>
            <source>source2</source>
            <destination>destination2</destination>
          </entry>
        </entries>
      </netmap>
    adapter_xml: |
      <adapter>
        <name>cd-adapter-11364</name>
        <type>exampleType</type>
        <host>{{ ssp_engine_host }}</host>
        <port>11364</port>
        <properties>
          <property>
            <name>adapterProperty</name>
            <value>adapterValue</value>
          </property>
        </properties>
      </adapter>

# POST https://localhost:8443/sspcmrest/sspcm/rest/policy/createPolicy
- name: Create Policy {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/policy/createPolicy
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ policy_xml }}"
    status_code: 200
    validate_certs: false
  when: create_policy
  register: policy_result

- name: Debug
  ansible.builtin.debug:
    msg:
      - "policy_result.status ................. {{ policy_result.status }}"
      - "policy_result.content ................. {{ policy_result.content }}"

- name: Create Netmap {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/netmap/createNetmap
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ netmap_xml }}"
    status_code: 200
    validate_certs: false
  when: create_netmap
  register: netmap_result

- name: Create Adapter {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/adapter/createAdapter
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ adapter_xml }}"
    status_code: 200
    validate_certs: false
  when: create_adapter
  register: adapter_result

# --------------------------------------------
# <netmapDef>
#   <description>Connect_Direct_Netmap</description>
#   <inboundNodes>
#     <inboundNodeDef>
#       <addresses>
#         <address>
#           <nodeName>ccenterdev03.irv.ustx.ibm.com</nodeName>
#           <host>ccenterdev03.irv.ustx.ibm.com</host>
#           <port>4163</port>
#         </address>
#       </addresses>
#       <description>ccenterdev03.irv.ustx.ibm.com</description>
#       <logLevel>NONE</logLevel>
#       <name>ccenterdev03.irv.ustx.ibm.com</name>
#       <outboundACLNodes>
#         <outboundACLNode>ccenterdev03.irv.ustx.ibm.com</outboundACLNode>
#       </outboundACLNodes>
#       <peerAddressPattern>ccenterdev03.irv.ustx.ibm.com</peerAddressPattern>
#       <policyId>CD_Policy_test</policyId>
#       <port>4163</port>
#       <routingName>ccenterdev03.irv.ustx.ibm.com</routingName>
#       <secureConnection>false</secureConnection>
#       <serverAddress>ccenterdev03.irv.ustx.ibm.com</serverAddress>
#       <tcpTimeout>90</tcpTimeout>
#     </inboundNodeDef>
#   </inboundNodes>
#   <name>CD_Netmap_test</name>
#   <outboundACLRequired>false</outboundACLRequired>
#   <protocol>cd</protocol>
#   <status></status>
# </netmapDef>

# --------------------------------------------
# <cdAdapterDef>
#   <encryptionLevel>false</encryptionLevel>
#   <engines></engines>
#   <faspPortrange>1000-2000</faspPortrange>
#   <listenPort>25000</listenPort>
#   <logLevel>DEBUG</logLevel>
#   <maxSessions>20</maxSessions>
#   <name>CD_Adapter_test</name>
#   <netmap>CD_Netmap_test</netmap>
#   <netmapKey>ccenterdev03.irv.ustx.ibm.com</netmapKey>
#   <properties></properties>
#   <protocol>cd</protocol>
#   <sessionTimeout>90</sessionTimeout>
#   <standardRoute>ccenterdev03.irv.ustx.ibm.com</standardRoute>
#   <status></status>
#   <urlRoutingType>standardRouting</urlRoutingType>
# </cdAdapterDef>
