---
- name: Define Facts
  ansible.builtin.set_fact:
    engine_xml: |
      <engineDef>
        <name>ssp-engine-01</name>
        <description><![CDATA[SSP Engine automated]]></description>
        <host>{{ ssp_engine_host }}</host>
        <port>{{ ssp_engine_port }}</port>
        <debugLogging>ERROR</debugLogging>
        <localPSLogging>ERROR</localPSLogging>
        <maverickLogging>ERROR</maverickLogging>
        <userStore>defUserStore</userStore>
        <blacklistUserIp></blacklistUserIp>
        <blacklistUserId></blacklistUserId>
        <properties>
          <property>
            <name>proxy.host.ip</name>
            <value></value>
          </property>
          <property>
            <name>ps.shutdown.timeout.secs</name>
            <value>60</value>
          </property>
        </properties>
      </engineDef>

# Create Engine on SSP
# -----------------------------------------------------------------------------------
- name: Create Engine on SSP
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/engine/createEngine
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ engine_xml }}"
    status_code: 200
    validate_certs: false
    return_content: true
  register: response
  # body: "{{ lookup('ansible.builtin.file','issue.json') }}"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "response.status ................. {{ response.status }}"
      - "response.content ................. {{ response.content }}"
