---
- name: Define Facts
  ansible.builtin.set_fact:
    config_name: "C:D"
    create_policy: "{{ ssp_config_cd.create_policy }}"
    create_netmap: "{{ ssp_config_cd.create_netmap }}"
    create_adapter: "{{ ssp_config_cd.create_adapter }}"
    policy_xml: |
        <cdPolicy>
          <name>cd-policy-test</name>
          <description><![CDATA[]]></description>
        </cdPolicy>
    policy_json: |
      {
        "policyName": "cd-policy",
        "description": "",
        "protocolErrorAction": "NONE",
        "userAuthentication": "none",
        "eaCertValidation": false,
        "userMapping": "noUserID",
        "type": "Connect Direct",
        "ipAddressCheck": false,
        "runJobStepAllowed": true,
        "runTaskStepAllowed": true,
        "copyStepAllowed": true,
        "submitStepAllowed": true,
        "protocol": "cd"
      }
    netmap_xml: |
      <netmap>
        <name>cd-netmap-01</name>
        <description><![CDATA[CD Netmap 01]]></description>
        <entries>
          <entry>
            <source>source1</source>
            <destination>destination1</destination>
          </entry>
          <entry>
            <source>source2</source>
            <destination>destination2</destination>
          </entry>
        </entries>
      </netmap>
    adapter_xml: |
      <adapter>
        <name>cd-adapter-11364</name>
        <type>exampleType</type>
        <host>{{ ssp_engine_host }}</host>
        <port>11364</port>
        <properties>
          <property>
            <name>adapterProperty</name>
            <value>adapterValue</value>
          </property>
        </properties>
      </adapter>

# # POST https://localhost:8443/sspcmrest/sspcm/rest/policy/createPolicy
# - name: Create Policy {{ config_name }}
#   ansible.builtin.uri:
#     url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/policy/createPolicy
#     method: POST
#     headers:
#       X-Authentication: "{{ session_token }}"
#       Content-Type: "application/xml"
#     body: "{{ policy_xml }}"
#     status_code: 200
#     validate_certs: false
#   when: create_policy
#   register: policy_result

- name: Create Policy Json {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/api/policy
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Accept: "application/json, text/plain, */*"
      Content-Type: "application/json"
    body: "{{ policy_json }}"
    body_format: json
    status_code: 200
    validate_certs: false
  when: create_policy
  register: policy_result

- name: Debug
  ansible.builtin.debug:
    msg:
      - "policy_result.status ................. {{ policy_result.status }}"

- name: Create Netmap {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/netmap/createNetmap
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ netmap_xml }}"
    status_code: 200
    validate_certs: false
  when: create_netmap
  register: netmap_result

- name: Create Adapter {{ config_name }}
  ansible.builtin.uri:
    url: https://{{ ssp_cm_url }}/sspcmrest/sspcm/rest/adapter/createAdapter
    method: POST
    headers:
      X-Authentication: "{{ session_token }}"
      Content-Type: "application/xml"
    body: "{{ adapter_xml }}"
    status_code: 200
    validate_certs: false
  when: create_adapter
  register: adapter_result

