---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create Session Token and SSP Engine
  ansible.builtin.include_tasks: 02_create_session.yml

- name: Config Engine on SSP
  ansible.builtin.include_tasks: configure_engine.yml
  when: ssp_config_engine

- name: Config Connect:Direct on SSP
  ansible.builtin.include_tasks: configure_cd.yml
  when: ssp_config_cd

- name: Config FTP on SSP
  ansible.builtin.include_tasks: configure_ftp.yml
  when: ssp_config_ftp

- name: Config HTTP on SSP
  ansible.builtin.include_tasks: configure_http.yml
  when: ssp_config_http

- name: Config MyFg on SSP
  ansible.builtin.include_tasks: configure_myfg.yml
  when: ssp_config_myfg

- name: Config SFTP on SSP
  ansible.builtin.include_tasks: configure_sftp.yml
  when: ssp_config_sftp
