---
- name: Define Sterling B2Bi helm chart values
  ansible.builtin.set_fact:
    sccm_helm_values:
      setupCfg:
        licenseAcceptEnableSfg: "true"
        licenseAcceptEnableFileOperation: "true"
        dbCreateSchema: "true"
        defaultDocumentStorageType: "DB"
      asi:
        ingress:
          internal:
            host: "{{ sccm_asccm_host }}"
      ac:
        ingress:
          internal:
            host: "{{ sccm_ac_host }}"
      api:
        ingress:
          internal:
            host: "{{ sccm_api_host }}"
      purge:
        schedule: "0 0 * * *"

- name: Generate my_values.yml
  ansible.builtin.template:
    src: "values.yaml.j2"
    dest: "{{ my_workdir }}/myb2bi_values.yml"

- name: Debug
  ansible.builtin.debug:
    msg: "helm install --timeout {{ sccm_helm.timeout }} -f {{ sccm_helm.values_yaml }} -n {{ sccm_namespace }} {{ sccm_helm.release }} {{ sccm_helm.chart }}"

# - name: Run Helm delete command
#   shell: "helm delete --namespace {{ sccm_namespace }} {{ sccm_helm_release }} {{ my_workdir }}/ibm-connect-direct/"

- name: Run Helm install command
  ansible.builtin.shell: 
    cmd: "helm install --timeout {{ sccm_helm.timeout }} -f {{ sccm_helm.values_yaml }} -n {{ sccm_namespace }} {{ sccm_helm.release }} {{ sccm_helm.chart }}"
# --timeout {{ sccm_helm.timeout }}
# --wait


# # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
# - name: Deploy Connect:Direct chart from local path
#   kubernetes.core.helm:
#     name: "{{ sccm_helm_release }}"
#     chart_ref: "{{ my_workdir }}/ibm-connect-direct/"
#     release_namespace: "{{ sccm_namespace }}"
#     wait: True
#     timeout: "{{ sccm_helm_timeout }}"
#     values_files:
#       - "{{ my_workdir }}/myb2bi_values.yml"

- name: "IBM Sterling Control Center Summary:"
  ansible.builtin.debug:
    msg:
      - "IBM Sterling Control Center status .............................. Ready!"
      - "IBM Sterling Control Center namespace ........................... {{ sccm_namespace }}"
      # - "Pod name ............................................ {{ sccm_pod_name }}"
      # - "For username and password check secret .............. {{ sccm_secret }}'"
