apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: ibm-itxa-anyuid-clusterrole
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - ibm-itxa-anyuid-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use
