---
# Environment variables
# -----------------------------------------------------------------------------------------------------------------
ssp_instanceid: "{{ lookup('env', 'SSP_INSTANCEID') }}"
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

ssp_version: "{{ lookup('env', 'SSP_VERSION') | default('6.1.0.0.03', true) }}"
ssp_license_type: "{{ lookup('env', 'SSP_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod

ssp_sys_passphrase: "{{ lookup('env', 'SSP_SYS_PASSPHRASE') | default('Passw0rd@', true) }}"
ssp_keycert_store_passphrase: "{{ lookup('env', 'SSP_KEYCERT_STORE_PASSPHRASE') | default('changeit', true) }}"
ssp_keycert_encrypt_passphrase: "{{ lookup('env', 'SSP_KEYCERT_ENCRYPT_PASSPHRASE') | default('Change1t@', true) }}"
ssp_custom_keycert_passphrase: "{{ lookup('env', 'SSP_CUSTOM_KEYCERT_PASSPHRASE') | default('Change1t@', true) }}"

ssp_timezone: "{{ lookup('env', ' SSP_TIMEZONE') | default('America/New_York', true) }}"
# lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=8)

# Configure instance
# -----------------------------------------------------------------------------
ssp_namespace: "ibm-ssp-{{ ssp_instanceid }}-engine"
ssp_cm_namespace: "ibm-ssp-{{ ssp_instanceid }}-cm"

entitled_registry: "cp.icr.io"
entitled_registry_user: cp

# Role Internal
# -----------------------------------------------------------------------------
my_workdir: /tmp

ssp_registry_secret: ibm-registry-secret
ssp_secret: ibm-ssp-secret
ssp_keycert_secretname: ibm-ssp-keycert
ssp_use_dynamic_provisioning: false
ssp_nameoverride: ssp-{{ ssp_instanceid }}

ssp_cm_keycert_secretname: ibm-ssp-cm-keycert

# Helm Variables
# -----------------------------------------------------------------------------
my_helm:
  release: "s0"
  timeout: "10m0s"
  values_yaml: "{{ my_workdir }}/myssp_values.yml"
  chart: "{{ my_workdir }}/ibm-ssp-engine"

# https://github.com/IBM/charts/tree/master/repo/ibm-helm
compatibility_matrix:
  6.1.0.0.03:
    helm_version: "1.3.4"
    image_repository: "cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image"
    image_tag: "6.1.0.0.03"

# Storage Class Matrix
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-file-gold"       # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: "gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: "managed-premium"
    rom: ""
    rwop: ""
  techzone:
    rwx: "managed-nfs-storage"
    rwx_nogid: "managed-nfs-storage"
    rwo: "managed-nfs-storage"
    rom: "managed-nfs-storage"
    rwop: "managed-nfs-storage"
