---
# Entitlement
# -----------------------------------------------------------------------------
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# SSP action
# ---------------------------------------------------------------------------
ssp_action: "{{ lookup('env', 'SSP_ACTION') | default('install', true) }}"

# Configure SSP instance
# -----------------------------------------------------------------------------------------------------------------
ssp_instanceid: "{{ lookup('env', 'SSP_INSTANCEID') }}"
ssp_version: "{{ lookup('env', 'SSP_VERSION') | default('6.2.1.0-iFix00-2025-07-04', true) }}"

ssp_license_type: "{{ lookup('env', 'SSP_LICENSE_TYPE') | default('non-prod', true) }}" # prod or no-prod
ssp_image_repository: "{{ lookup('env', 'SSP_IMAGE_REPOSITORY') | default('cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image', true) }}"
ssp_skip_image_secret: "{{ lookup('env', 'SSP_SKIP_IMAGE_SECRET') | default(false, true) }}"
ssp_sys_passphrase: "{{ lookup('env', 'SSP_SYS_PASSPHRASE') | default('Password123!', true) }}"
ssp_keycert_store_passphrase: "{{ lookup('env', 'SSP_KEYCERT_STORE_PASSPHRASE') | default('changeit', true) }}"
ssp_keycert_encrypt_passphrase: "{{ lookup('env', 'SSP_KEYCERT_ENCRYPT_PASSPHRASE') | default('Change1t@', true) }}"
ssp_custom_keycert_passphrase: "{{ lookup('env', 'SSP_CUSTOM_KEYCERT_PASSPHRASE') | default('Change1t@', true) }}"

ssp_timezone: "{{ lookup('env', ' SSP_TIMEZONE') | default('America/New_York', true) }}"
# lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=8)

ssp_skip_helm: "{{ lookup('env', 'SSP_SKIP_HELM') | default(false, true) }}"

# Storage
# -----------------------------------------------------------------------------
ssp_storage_class: "{{ lookup('env', 'SSP_STORAGE_CLASS') }}"

# Configure instance
# -----------------------------------------------------------------------------
ssp_namespace: "ibm-ssp-{{ ssp_instanceid }}-engine"
ssp_cm_namespace: "ibm-ssp-{{ ssp_instanceid }}-cm"


# Role Internal
# -----------------------------------------------------------------------------
my_workdir: /tmp

ssp_registry_secret: ibm-registry-secret
ssp_secret: ibm-ssp-secret
ssp_keycert_secret: ssp-cm-keycert
ssp_use_dynamic_provisioning: false
ssp_nameoverride: ssp-{{ ssp_instanceid }}

ssp_generate_certificates: false

# https://github.com/IBM/charts/tree/master/repo/ibm-helm
compatibility_matrix:
  6.2.1.0-iFix00-2025-07-04:
    helm_version: "1.6.0"
    image_tag: "6.2.1.0-iFix00-2025-07-04"
  6.2.0.1.02:
    helm_version: "1.5.4"
    image_tag: "6.2.0.1.02"
    affinity_default: "{}"
  6.2.0.0.01:
    helm_version: "1.5.1"
    image_tag: "6.2.0.0.01"
    affinity_default: "{}"
  6.2.0.0:
    helm_version: "1.4.0"
    image_tag: "6.2.0.0"
    affinity_default: "{}"
  6.1.0.0.04:
    helm_version: "1.3.6"
    image_tag: "6.1.0.0.04"
    affinity_default: "[]"
  6.1.0.0.03plus:
    helm_version: "1.3.5"
    image_tag: "6.1.0.0.03plus"
    affinity_default: "[]"

# Storage Class Matrix
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-file-gold"       # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: "gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefile-premium"
    rwx_nogid: "azurefile-premium"
    rwo: "managed-premium"
    rom: ""
    rwop: ""
  techzone:
    rwx: "managed-nfs-storage"
    rwx_nogid: "managed-nfs-storage"
    rwo: "managed-nfs-storage"
    rom: "managed-nfs-storage"
    rwop: "managed-nfs-storage"
  ibm-spectrum:
    rwx: "scale-cnsa"
    rwx_nogid: "scale-cnsa"
    rwo: "scale-cnsa"
    rom: "scale-cnsa"
    rwop: "scale-cnsa"
  nfs:
    rwx: "nfs"
    rwx_nogid: "nfs"
    rwo: "nfs"
    rom: "nfs"
    rwop: "nfs"
  ibm-fyre1:
    rwx: "rook-cephfs"
    rwx_nogid: "rook-cephfs"
    rwo: "rook-cephfs" # rook-ceph-block
    rom: ""
    rwop: ""
