---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for MQ"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ mq_namespace }}"
  register: cout

# Create ServiceAccount for MQueue
# -----------------------------------------------------------------------------
- name: Create Service Account for MQ
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ mq_service_account }}"
        namespace: "{{ mq_namespace }}"

- name: Add privileged SCC to service account
  ansible.builtin.command: oc adm policy add-scc-to-user privileged -n {{ mq_namespace }} -z {{ mq_service_account }}
  changed_when: false

# FIXME: Need to migrate to kubernetes.core.k8s module
# - name: Add privileged SCC to service account
#   kubernetes.core.k8s:
#     state: present
#     definition:
#       apiVersion: security.openshift.io/v1
#       kind: SecurityContextConstraints
#       metadata:
#         name: "{{mq_service_account}}"
#         namespace: "{{ mq_namespace }}"
#       users:
#         - system:serviceaccount:{{ mq_namespace }}:{{ mq_name }}
#       allowPrivilegedContainer: true

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: Create secret content '{{ mq_registry_secret }}'
  no_log: true
  vars:
    entitled_auth_str: "{{ entitled_registry_user }}:{{ entitled_registry_key }}"
    entitled_auth_b64: "{{ entitled_auth_str | b64encode }}"
    content:
      - '{"auths":{"{{ entitled_registry }}":{"username":"{{ entitled_registry_user }}","password":"{{ entitled_registry_key }}",'
      - '"email":"{{ entitled_registry_user }}","auth":"{{ entitled_auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate secret '{{ mq_registry_secret }}'"
  no_log: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ mq_registry_secret }}"
        namespace: "{{ mq_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: ibm_registry_secret_cout

- name: "Generate secret '{{ mq_secret }}'"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ mq_secret }}"
        namespace: "{{ mq_namespace }}"
      data:
        adminPassword: "{{ mq_admin_password | b64encode }}"
        appPassword: "{{ mq_app_password | b64encode }}"
