---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets for MQ
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Define Storage for Data Persistence
  ansible.builtin.include_tasks: 03_define_storage.yml

- name: Install MQ for Sterling Partner Enagement
  ansible.builtin.include_tasks: 04_install_mq.yml
