---
- name: Check if DB2 Server is already up and running
  ansible.builtin.shell: "ps -ef | grep db2 | grep -v grep"
  changed_when: true
  register: __db2_running
  failed_when: false

- name: Check if Product already Installed?
  ansible.builtin.shell: "{{ __db2_install_path }}/adm/db2licm -l"
  changed_when: true
  register: __db2_installed
  failed_when: false
# when: not __db2_installed.stat.exists
