---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for MQ"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ mq_namespace }}"
  register: cout

# Create ServiceAccount for MQueue
# -----------------------------------------------------------------------------
- name: Create Service Account for MQ
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{mq_service_account}}"
        namespace: "{{ mq_namespace }}"

- name: Add privileged SCC to service account
  ansible.builtin.command: oc adm policy add-scc-to-user privileged -n {{ mq_namespace }} -z {{ mq_service_account }}

# FIXME: Need to migrate to kubernetes.core.k8s module
# - name: Add privileged SCC to service account
#   kubernetes.core.k8s:
#     state: present
#     definition:
#       apiVersion: security.openshift.io/v1
#       kind: SecurityContextConstraints
#       metadata:
#         name: "{{mq_service_account}}"
#         namespace: "{{ mq_namespace }}"
#       users:
#         - system:serviceaccount:{{ mq_namespace }}:{{ mq_name }}
#       allowPrivilegedContainer: true

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: Create '{{ mq_registry_secret }}' secret content
  no_log: true
  vars:
    entitledAuthStr: "{{ entitled.registry_user }}:{{ entitled.registry_key }}"
    entitledAuth: "{{ entitledAuthStr | b64encode }}"
    content:
      - "{\"auths\":{\"{{ entitled.registry }}\":{\"username\":\"{{ entitled.registry_user }}\",\"password\":\"{{ entitled.registry_key }}\",\"email\":\"{{ entitled.registry_user }}\",\"auth\":\"{{ entitledAuth }}\"}"
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate '{{ mq_registry_secret }}' secret"
  no_log: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ mq_registry_secret }}"
        namespace: "{{ mq_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: ibm_registry_secret_cout

- name: "Generate '{{ mq_secret }}' secret"
  no_log: false
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ mq_secret }}"
        namespace: "{{ mq_namespace }}"
      data:
       adminPassword: "{{ mq_admin_password | b64encode }}"
       appPassword: "{{ mq_app_password | b64encode }}"
