---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for Connect:Direct"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cdws_namespace }}"
  register: cout

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: Create secret content
  no_log: true
  vars:
    entitled_auth_str: "{{ entitled_registry_user }}:{{ entitled_registry_key }}"
    entitled_auth_b64: "{{ entitled_auth_str | b64encode }}"
    content:
      - '{"auths":{"{{ entitled_registry }}":{"username":"{{ entitled_registry_user }}","password":"{{ entitled_registry_key }}",'
      - '"email":"{{ entitled_registry_user }}","auth":"{{ entitled_auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: "Generate secret '{{ cdws_registry_secret }}'"
  no_log: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ cdws_registry_secret }}"
        namespace: "{{ cdws_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"

- name: "Generate CDWS secret '{{ cdws_secret }}'"
  no_log: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Generic
      metadata:
        name: "{{ cdws_secret }}"
        namespace: "{{ cdws_namespace }}"
      data:
        trustStorePassword: "{{ cdws_truststore_password | b64encode }}"
        keyStorePassword: "{{ cdws_keystore_password | b64encode }}"
        caCertPassword: "{{ cdws_cacert_password | b64encode }}"
