---
# 3. Set Storage Class
# -----------------------------------------------------------------------------
- name: Default Kafka Storage for ROKS if not set by user
  when: kafka_storage_class is not defined or kafka_storage_class == ""
  ansible.builtin.set_fact:
    kafka_storage_class: "{{ storage_class_matrix[my_storage_class].rwo }}"

- name: Assert that kafka storage class has been defined
  ansible.builtin.assert:
    that: kafka_storage_class is defined and kafka_storage_class != ""
    fail_msg: "kafka_storage_class must be defined"

- name: Default Zookeeper Storage for ROKS if not set by user
  when: zookeeper_storage_class is not defined or zookeeper_storage_class == ""
  ansible.builtin.set_fact:
    zookeeper_storage_class: "{{ storage_class_matrix[my_storage_class].rwo }}"

- name: Assert that zookeeper storage class has been defined
  ansible.builtin.assert:
    that: zookeeper_storage_class is defined and zookeeper_storage_class != ""
    fail_msg: "zookeeper_storage_class must be defined"

# 3. Debug storage class configuration
# -----------------------------------------------------------------------------
- name: "Debug Kafka storage classes configuration"
  ansible.builtin.debug:
    msg:
      - "Storage class (kafka) ...... {{ kafka_storage_class }}"
      - "Storage class (zookeeper) .. {{ zookeeper_storage_class }}"
