---
# Environment variables
# -----------------------------------------------------------------------------------------------------------------
itx_rs_namespace: "{{ lookup('env', 'ITX_RS_NAMESPACE') }}"
itx_rs_instanceid: "{{ lookup('env', 'ITX_RS_INSTANCEID') }}"
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

itx_rs_version: "{{ lookup('env', 'ITX_RS_VERSION') | default('10.1.2.0.20231130', true) }}"

itx_rs_sys_passphrase: "{{ lookup('env', 'ITX_RS_SYS_PASSPHRASE') | default('Passw0rd@', true) }}"

# Configure instance
# -----------------------------------------------------------------------------
entitled_registry: "cp.icr.io"
entitled_registry_user: cp

# Role Internal
# -----------------------------------------------------------------------------
my_workdir: /tmp

itx_rs_registry_secret: ibm-registry-secret
itx_rs_secret: ibm-itx-rs-secret

# https://github.com/IBM/charts/tree/master/repo/ibm-helm
compatibility_matrix:
  10.1.2.0.20231130:
    helm_version: "2.1.0"
    image_tag: "10.1.2.0.20231130"

# Storage Class Matrix
# -----------------------------------------------------------------------------
storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-file-gold"       # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: "gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: "managed-premium"
    rom: ""
    rwop: ""
  techzone:
    rwx: "managed-nfs-storage"
    rwx_nogid: "managed-nfs-storage"
    rwo: "managed-nfs-storage"
    rom: "managed-nfs-storage"
    rwop: "managed-nfs-storage"
