---
- name: Check for required environment variables
  ansible.builtin.assert:
    that:
      # CONNECT:DIRECT
      - lookup('env', 'ITXA_NAMESPACE') != ""
      # IBM
      - lookup('env', 'ENTITLED_REGISTRY_KEY') != ""
    fail_msg: "One or more required environment variables are not defined"

# Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if itxa_namespace is not provided"
  ansible.builtin.assert:
    that: itxa_namespace is defined and itxa_namespace != ""
    fail_msg: "itxa_namespace property is required"

- name: "Fail if entitled_registry_key is not provided"
  ansible.builtin.assert:
    that: entitled_registry_key is defined and entitled_registry_key != ""
    fail_msg: "entitled_registry_key property is required"

- name: Unique Id for files
  ansible.builtin.set_fact:
    my_serial: "{{ lookup('password', '/dev/null length=8 chars=ascii_lowercase,digits') }}"

# Debug
# -----------------------------------------------------------------------------
- name: Debug
  ansible.builtin.debug:
    msg:
      - "Kubernets Namespace ................. {{ itxa_namespace }}"
      - "my_serial ........................... {{ my_serial }}"
