---
- name: "Create Kubernetes Route {{ itxa_route_web }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ itxa_route_web }}"
        namespace: "{{ itxa_namespace }}"
        labels:
          app.kubernetes.io/instance: s0
          app.kubernetes.io/name: ibm-itxa
          release: s0
      spec:
        path: "/spe/myspe"
        to:
          kind: Service
          name: "{{ itxa_svc_web }}"
        port:
          targetPort: http
        tls:
          termination: edge
        wildcardPolicy: None
