---
# Configure Db2 instance
# -----------------------------------------------------------------------------------------------------------------
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('sterling-b2bi-db2-dev', true) }}"

db2_instance_name: "{{ lookup('env', 'DB2_INSTANCE_NAME') | default('db2inst1', true) }}"
db2_user: "{{ lookup('env', 'DB2_USER') | default('db2inst1', true) }}"
db2_password: "{{ lookup('env', 'DB2_USER') | default('passw0rd', true) }}"
db2_dbname: "{{ lookup('env', 'DB2_DBNAME')   | default('B2BI', true) }}"
db2_version: "{{ lookup('env', 'DB2_VERSION') | default('11.5.5.1', true)}}"

# Entitlement
# -----------------------------------------------------------------------------
entitled:
  registry: "cp.icr.io"
  registry_user: cp
  registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Others
# -----------------------------------------------------------------------------
db2_registry_secret: mydb2-ibm-registry-secret
db2_service_account: mydb2-sa
db2_secret: mydb2-secret
db2_prefix: mydb2

storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: " ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: " gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: " managed-premium"
    rom: ""
    rwop: ""
