# check_openshift.yml
---
- name: "Check required variables"
  assert:
    that:
      - repository_url is defined and repository_url != ''
      - sb2bi_package is defined and sb2bi_package != ''
    fail_msg: "One or more required variables are not defined"
