---
# Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: Check for required environment variables
  ansible.builtin.assert:
    that:
      - lookup('env', 'PEM_INSTANCEID') != ""
      - lookup('env', 'ENTITLED_REGISTRY_KEY') != ""
      - entitled_registry_key is defined and entitled_registry_key != ""
    fail_msg: "One or more required environment variables are not defined"

- name: "Fail pem_instanceid is 'not provided' or 'has uppercase characters'"
  ansible.builtin.assert:
    that:
      - pem_instanceid is defined and pem_instanceid != ""
      - pem_instanceid is match('[a-z0-9-]+')
    fail_msg: "Property 'pem_instanceid' is greater than 8 character long or has uppercase characters"

# Check Supported version
# -----------------------------------------------------------------------------
- name: Get Cluster information
  kubernetes.core.k8s_cluster_info:
  register: k8s_cluster_info

- name: Extract Kubernetes version number
  ansible.builtin.set_fact:
    k8s_version: "{{ k8s_cluster_info.version.server.kubernetes.major }}.{{ k8s_cluster_info.version.server.kubernetes.minor }}"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "PEM version  ...................... {{ pem_version }}"
      - "Kubernetes Cluster version ........ {{ k8s_version }}"

# - name: Ensure Sterling PEM is supported in Kubernetes Cluster
#   ansible.builtin.assert:
#     that:
#       - pem_version != ""
#       - k8s_version != ""
#       - "k8s_version is version( compatibility_matrix[pem_version].k8s_min_version, '>=')"
#       - "k8s_version is version( compatibility_matrix[pem_version].k8s_max_version, '<=')"
#     fail_msg: "Sterling PEM version is NOT supported in current Kubernetes Cluster"
#   when: not pem_skip_helm

# Lookup Namespace availabiity
# -----------------------------------------------------------------------------
- name: Lookup Namespaces
  kubernetes.core.k8s_info:
    kind: Namespace
  register: lookup_namespaces

- name: Create List of Namespaces
  ansible.builtin.set_fact:
    namespace_list: "{{ lookup_namespaces.resources | map(attribute='metadata.name') | list }}"

# 3. Check for DB Information
# -----------------------------------------------------------------------------
- name: Check for DB2 provided namespace
  ansible.builtin.set_fact:
    db2_namespace: "{{ env_db2_namespace }}"
  when:
    - env_db2_namespace is defined and env_db2_namespace != ""
    - env_db2_namespace in namespace_list

- name: Check for DB2 default namespace
  ansible.builtin.set_fact:
    db2_namespace: "{{ pem_db2_namespace }}"
  when:
    - db2_namespace == ""
    - pem_db2_namespace in namespace_list

- name: "Fail if Database Information is not provided"
  ansible.builtin.assert:
    that:
      - (db2_namespace != "") or (pem_dbvendor != "")
    fail_msg: "Database Information property is required"

# 4. Check for MQ Information
# -----------------------------------------------------------------------------
- name: Check for MQ provided namespace
  ansible.builtin.set_fact:
    mq_namespace: "{{ env_mq_namespace }}"
  when:
    - env_mq_namespace is defined and env_mq_namespace != ""
    - env_mq_namespace in namespace_list

- name: Check for MQ default namespace
  ansible.builtin.set_fact:
    mq_namespace: "{{ pem_mq_namespace }}"
  when:
    - mq_namespace == ""
    - pem_mq_namespace in namespace_list

- name: "Fail if JMS Queue Information is not provided"
  ansible.builtin.assert:
    that:
      - (mq_namespace != "") or (pem_jmsuser != "")
    fail_msg: "JMS Queue Information property is required"

# 5. Serial ID
# -----------------------------------------------------------------------------
- name: Unique Id for files
  ansible.builtin.set_fact:
    my_serial: "{{ lookup('password', '/dev/null length=8 chars=ascii_lowercase,digits') }}"

# Debug
# -----------------------------------------------------------------------------
- name: Debug
  ansible.builtin.debug:
    msg:
      - "PEM Instance ID  .............. {{ pem_instanceid }}"
      - "PEM namespace ................. {{ pem_namespace }}"
      - "Database Namespace ............ {{ db2_namespace }}"
      - "JMS Queue Namespace ........... {{ mq_namespace }}"
      - "my_serial ..................... {{ my_serial }}"
