---
# Currently supported providers are standard
minio_provider: "{{ lookup('env', 'MINIO_PROVIDER') | default('standard', true) }}"
minio_action: "{{ lookup('env', 'MINIO_ACTION') | default('install', true) }}"

minio_namespace: "{{ lookup('env', 'MINIO_NAMESPACE') | default('sterling-minio', true) }}"

minio_root_user: "{{ lookup('env', 'MINIO_ROOT_USER') | default('root', true) }}"
minio_root_password: "{{ lookup('env', 'MINIO_ROOT_PASSWORD') | default('passw0rd', true) }}"
minio_storage_size: "{{ lookup('env', 'MINIO_STORAGE_SIZE') | default('10Gi', true) }}"


storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: "ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: "gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: "managed-premium"
    rom: ""
    rwop: ""
  techzone:
    rwx: "managed-nfs-storage"
    rwx_nogid: "managed-nfs-storage"
    rwo: "managed-nfs-storage"
    rom: "managed-nfs-storage"
    rwop: "managed-nfs-storage"
  ibm-spectrum:
    rwx: "scale-cnsa"
    rwx_nogid: "scale-cnsa"
    rwo: "scale-cnsa"
    rom: "scale-cnsa"
    rwop: "scale-cnsa"
