---
# Create Kubernetes namespace
# -----------------------------------------------------------------------------
- name: "Create namespace for SSP Perimeter Server"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ssp_ps_namespace }}"
  register: cout

# Create Secrets on Kubernetes
# -----------------------------------------------------------------------------
- name: "Skip CM Image Secrect"
  ansible.builtin.set_fact:
    ssp_registry_secret: ""
  when: ssp_ps_skip_image_secret

- name: Create secret content
  no_log: true
  vars:
    entitled_auth_str: "cp:{{ entitled_registry_key }}"
    entitled_auth_b64: "{{ entitled_auth_str | b64encode }}"
    content:
      - '{"auths":{"cp.icr.io":{"username":"cp","password":"{{ entitled_registry_key }}",'
      - '"email":"cp","auth":"{{ entitled_auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"
  when: not ssp_ps_skip_image_secret

- name: "Generate secret '{{ ssp_ps_deploy_registry_secret }}'"
  no_log: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ ssp_ps_deploy_registry_secret }}"
        namespace: "{{ ssp_ps_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  when: not ssp_ps_skip_image_secret

# - name: "Generate SSP CM secret '{{ ssp_ps_deploy_secret }}'"
#   no_log: true
#   kubernetes.core.k8s:
#     definition:
#       apiVersion: v1
#       kind: Secret
#       type: Generic
#       metadata:
#         name: "{{ ssp_ps_deploy_secret }}"
#         namespace: "{{ ssp_ps_namespace }}"
#       data:
#         sysPassphrase: "{{ ssp_ps_sys_passphrase | b64encode }}"
#         adminPassword: "{{ ssp_ps_admin_password | b64encode }}"
#         keyStorePassphrase: "{{ ssp_ps_keystore_passphrase | b64encode }}"
#         trustStorePassphrase: "{{ ssp_ps_truststore_passphrase | b64encode }}"
