---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets for SSP CM
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Applying Pod Security
  ansible.builtin.include_tasks: 03_apply_pod_security.yml

- name: Install SSP PS using Helm Chart
  ansible.builtin.include_tasks: 04_install_ssp_ps.yml
