---
- name: Cleanup Namespace ibm-b2bi-dev
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Delete Namespace ibm-b2bi-dev
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ibm-b2bi-mq-dev
