---
- name: Cleanup Namespace sterling-cdnode01-dev
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars:
    cd_namespace: "{{ lookup('env', 'CD_NAMESPACE') | default('sterling-cdnode01-dev', true) }}"
    my_workdir: /tmp
    cd_helm_version: 1.3.5
  tasks:
    - name: Delete Namespace sterling-cdnode01-dev
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ cd_namespace }}"

    - name: "Cleanup directories and files"
      ansible.builtin.file:
        path: "{{ my_workdir }}/ibm-connect-direct-{{ cd_helm_version }}"
        state: absent
      with_items:
        - "{{ my_workdir }}/ibm-connect-direct-{{ cd_helm_version }}.tgz"
        - "{{ my_workdir }}/ibm-connect-direct"
        - "{{ my_workdir }}/mycd_values.yml"
        - "{{ my_workdir }}/cdcert.pem"
        - "{{ my_workdir }}/cdcert.crt"
        - "{{ my_workdir }}/cdcert.cer"
