# Delete directories - BE CAREFULL
#
# ansible-playbook -i environments/hosts.development -u <username> -k playbooks/ibm-was-nd/was-delete-all.yml
---
- hosts:                    cd_servers
  become:                   true
  vars:
    __cd_user:              "cduser1"
    __cd_group:             "cduser1"
  tasks:
#    - name:          KillAll Java
#      command:       killall -9 java
#      register:      cout
#      #with_items:
#      #- "{{ __ibm_dir }}/Connections"
#      ignore_errors: true

    - name:                  "Cleanup All directories"
      file:
        path:                "{{ item }}"
        state:               absent
      with_items:
        - /opt/IBM/Binaries
        - /opt/IBM/cdunix
        - /opt/IBM/workdir
      ignore_errors: true

    - name:           Delete cd user
      user:
        name:         "{{ __cd_user }}"
        group:        "{{ __cd_group }}"
        state:        absent

    - name:           Delete cd group
      group:
        name:         "{{ __cd_group }}"
        state:        absent

