---
# Configure Db2 instance
# -----------------------------------------------------------------------------------------------------------------
si_instanceid: "{{ lookup('env', 'SI_INSTANCEID') }}"
db2_namespace: "{{ db2_namespace |  default('sterling-b2bi-' + si_instanceid + '-db2', true) }}"
db2_password: "{{ lookup('env', 'DB2_PASSWORD') | default('passw0rd', true) }}"
db2_version: "{{ lookup('env', 'DB2_VERSION') | default('11.5.9.0', true)}}"

db2_instance_name: "{{ db2_instance_name |  default('db2inst1', true) }}"
db2_user: "{{ db2_user |  default('db2inst1', true) }}"
db2_dbname: "{{ db2_dbname |  default('B2BI', true) }}"

# Entitlement
# -----------------------------------------------------------------------------
entitled_registry: "cp.icr.io"
entitled_registry_user: cp
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# Others
# -----------------------------------------------------------------------------
db2_registry_secret: mydb2-ibm-registry-secret
db2_service_account: mydb2-sa
db2_secret: mydb2-secret
db2_id: mydb2

db2_storage_size: "10Gi" # 40Gi

storage_class_matrix:
  ibmcloud:
    rwx: "ibmc-file-gold-gid"   # ReadWriteMany
    rwx_nogid: "ibmc-file-gold" # ReadWriteMany no GID
    rwo: "ibmc-block-gold"      # ReadWriteOnce
    rom: ""                     # ReadOnlyMany
    rwop: ""                    # ReadWriteOncePod
  redhat:
    rwx: "ocs-storagecluster-cephfs"
    rwx_nogid: "ocs-storagecluster-cephfs"
    rwo: " ocs-storagecluster-ceph-rbd"
    rom: ""
    rwop: ""
  aws:
    rwx: "efs"
    rwx_nogid: "efs"
    rwo: " gp2"
    rom: ""
    rwop: ""
  azure:
    rwx: "azurefiles-premium"
    rwx_nogid: "azurefiles-premium"
    rwo: " managed-premium"
    rom: ""
    rwop: ""
