---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

# 2. Determine which pod to run in
# -----------------------------------------------------------------------------
- name: Determine which pod to run in
  ansible.builtin.include_tasks: 02_lookup_pods.yml

# 3. Prepare database for use with IBM Sterling Control Center Director
# -----------------------------------------------------------------------------
- name: Prepare database for use with IBM Sterling Control Center Director
  ansible.builtin.include_tasks: 03_setup_db.yml
