---
# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if minio_provider is not provided"
  ansible.builtin.assert:
    that: minio_provider is defined and minio_provider != ""
    fail_msg: "minio_provider property is required"

- name: Configure MinIO variables
  ansible.builtin.debug:
    msg:
      - "MinIO Provider .................. {{ minio_provider }}"

- name: Run the install / uninstall for specified provider
  ansible.builtin.include_tasks: "tasks/provider/{{ minio_provider }}/{{ minio_action }}.yml"
  when:
    - minio_action != "none"
