apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ibm-ssp-ps-scc"
  labels:
    app.kubernetes.io/name: ibm-ssp-ps-scc
    app.kubernetes.io/instance: ibm-ssp-ps-scc
    app.kubernetes.io/managed-by: IBM
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - ibm-ssp-ps-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
