apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ibm-ssp-ps-psp
  labels:
    app: "ibm-ssp-ps-psp"
spec:
  privileged: false
  allowPrivilegeEscalation: true
  hostPID: false
  hostIPC: false
  hostNetwork: false
  requiredDropCapabilities:
    - KILL
    - MKNOD
    - SETFCAP
    - FSETID
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - SETPCAP
    - NET_RAW
  allowedCapabilities:
    - DAC_OVERRIDE
    - SETGID
  allowedHostPaths:
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 4294967294
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 4294967294
  volumes:
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
    - persistentVolumeClaim
    - nfs
  forbiddenSysctls:
    - "*"
