---
# Entitlement
# -----------------------------------------------------------------------------
entitled_registry_key: "{{ lookup('env', 'ENTITLED_REGISTRY_KEY') }}"

# SSP action
# ---------------------------------------------------------------------------
ssp_ps_action: "{{ lookup('env', 'SSP_ACTION') | default('install', true) }}"

# Configure SSP instance
# -----------------------------------------------------------------------------------------------------------------
ssp_instanceid: "{{ lookup('env', 'SSP_INSTANCEID') }}"

ssp_ps_version: "{{ lookup('env', 'SSP_VERSION') | default('6.2.0.1.02', true) }}"

ssp_ps_license_type: "{{ lookup('env', 'SSP_LICENSETYPE') | default('non-prod', true) }}" # prod or no-prod

ssp_ps_skip_image_secret: "{{ lookup('env', 'SSP_PS_SKIP_IMAGE_SECRET') | default(false, true) }}"

# Others
# -----------------------------------------------------------------------------
my_workdir: /tmp

ssp_ps_namespace: "ibm-ssp-{{ ssp_instanceid }}-ps"
ssp_namespace: "ibm-ssp-{{ ssp_instanceid }}-engine"
ssp_cm_namespace: "ibm-ssp-{{ ssp_instanceid }}-cm"

ssp_ps_deploy_registry_secret: ibm-registry-secret
ssp_ps_deploy_secret: ibm-ssp-ps-secret
ssp_keycert_secret: ssp-cm-keycert
ssp_ps_use_dynamic_provisioning: false

# https://github.com/IBM/charts/tree/master/repo/ibm-helm
compatibility_matrix:
  6.2.0.1.02:
    helm_version: "1.5.4"
    image_tag: "6.2.0.1.02"
  6.2.0.0.01:
    helm_version: "1.5.1"
    image_tag: "6.2.0.0.01"
  6.2.0.0:
    helm_version: "1.4.0"
    image_tag: "6.2.0.0"
