---
- name: Is IBM Java SDK already Installed?
  ansible.builtin.stat:
    path: "{{ __sdk_install_path }}/bin/java"
  register: __sdk_installed

- name: Is IBM Installation Manager already Installed?
  ansible.builtin.stat:
    path: "{{ __iim_install_path }}/eclipse/tools/imcl"
  register: __iim_installed

- name: Is IBM Sterling B2Bi already Installed?
  ansible.builtin.stat:
    path: "{{ __si_install_path }}/bin/run.sh"
  register: __sb2b_installed
