---
openldap_namespace: "{{ lookup('env', 'OPENLDAP_NAMESPACE') | default('sterling-openldap', true) }}"
phpldapadmin_namespace: "{{ lookup('env', 'PHPLDAPADMIN_NAMESPACE') | default('sterling-phpldapadmin', true) }}"

openldap_host: "openldap-svc.{{ openldap_namespace }}.svc.cluster.local"

ldp_admin_password: "{{ lookup('env', 'OPENLDAP_ADMIN_PASSW0RD') | default('passw0rd', true) }}"

phpldapadmin_image: docker.io/osixia/phpldapadmin:latest
