- name: Deploy IBM Sterling B2B Integrator on RedHat OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    - sb2bi_deploy_db2
    - sb2bi_prebuiltdb_db2
    - sb2bi_deploy_mq
    - sb2bi_deploy
