---
# Setup Nginx
# 
# 
# We use an Nginx HTTP server to download files
# ansible-playbook -i environments/examples/cd-servers.dev.sample -u root playbooks/setup-nginx.yml
#
# After Install copy files to /usr/shared/nginx/html
- name: Install Nginx HTTP server to download files
  hosts: nginx_servers
  any_errors_fatal: true
  become: true
  roles:
    - roles/others/nginx-install
