---
- name: Debug Certificate Manager
  ansible.builtin.debug:
    msg:
      - "Action ................................... {{ cert_manager_action }}"
      - "Provider ................................. {{ cert_manager_provider }}"
      - "Operator Namespace ....................... {{ cert_manager_operator_namespace }}"
      - "Operand Namespace ........................ {{ cert_manager_namespace }}"
      - "Channel .................................. {{ cert_manager_channel }}"

- name: "Execute the chosen action"
  ansible.builtin.include_tasks: "tasks/provider/{{ cert_manager_provider }}/{{ cert_manager_action }}.yml"
  when: cert_manager_action != "none"
