# Configure Db2 instance
# -----------------------------------------------------------------------------------------------------------------
scc_instanceid: "{{ lookup('env', 'SCC_INSTANCEID') }}"
scc_products: "{{ lookup('env', 'SCC_PRODUCTS') | default('', true) }}" # productEntitlement: "CCD,CCM"

db2_namespace: "ibm-scc-{{ scc_instanceid }}-db2"

db2_instance_name: "db2inst1"
db2_user: "db2inst1"
db2_container: "mydb2"

# Others
# -----------------------------------------------------------------------------
my_workdir: /tmp

scc_products_upper: "{{ scc_products | upper }}"
