---
- name: "Cleanup directories and files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ my_workdir }}/ibm-itx-rs-prod-{{ compatibility_matrix[itx_rs_version].helm_version }}.tgz"
    # - "{{ my_workdir }}/myitx_rs_values.yml"

- name: "Download Helm chart"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-itx-rs-prod-{{ compatibility_matrix[itx_rs_version].helm_version }}.tgz"
    dest: "{{ my_workdir }}/ibm-itx-rs-prod-{{ compatibility_matrix[itx_rs_version].helm_version }}.tgz"
    mode: "0640"
  register: download_cout
  until: download_cout is succeeded
  retries: 3

# Check for Kubernetes Resources and APIs
# -----------------------------------------------------------------------------
- name: Get Cluster information
  kubernetes.core.k8s_cluster_info:
  register: k8s_cl_info

- name: Check for SCC Resource
  ansible.builtin.set_fact:
    scc_resource: false
    scc_apiversion: false
    psp_resource: false
    psp_apiversion: false

- name: Check for SCC Resource
  ansible.builtin.set_fact:
    scc_resource: true
  when: "'security.openshift.io/v1' in k8s_cl_info.apis"

- name: Check if SCC API version
  ansible.builtin.set_fact:
    scc_apiversion: true
  when:
    - scc_resource
    - "'SecurityContextConstraints' in k8s_cl_info.apis['security.openshift.io/v1']"

- name: Check for PSP Resource
  ansible.builtin.set_fact:
    psp_resource: true
  when: "'policy/v1beta1' in k8s_cl_info.apis"

- name: Check if PSP API version
  ansible.builtin.set_fact:
    psp_apiversion: true
  when:
    - psp_resource
    - "'PodSecurityPolicy' in k8s_cl_info.apis['policy/v1beta1']"

# Debug
# -----------------------------------------------------------------------------
- name: Debug Apply Pod Security
  ansible.builtin.debug:
    msg:
      - "scc_resource ................. {{ scc_resource }}"
      - "scc_apiversion ............... {{ scc_apiversion }}"
      - "psp_resource ................. {{ psp_apiversion }}"
      - "psp_apiversion ............... {{ psp_apiversion }}"

# Creating Pod Security Policy for Kubernetes Cluster
# -----------------------------------------------------------------------------
- name: Creating Security Context Constraints
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'files/ibm-itx-rs-scc.yaml') | from_yaml }}"
  when: scc_resource and scc_apiversion

- name: Add SCC to group for target namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: ibm-itx-rs-scc
      groups:
        - "system:serviceaccounts:{{ itx_rs_namespace }}"
