---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Create namespace and secrets for ITX
  ansible.builtin.include_tasks: 02_create_namespace_secrets.yml

- name: Applying Pod Security
  ansible.builtin.include_tasks: 03_apply_pod_security.yml

- name: Define Storage for Data Persistence
  ansible.builtin.include_tasks: 04_define_storage.yml

- name: Install ITX using Helm Chart
  ansible.builtin.include_tasks: 05_install_itx_rs.yml
